# 0326 LangGraph Smoketest

Smoke test for `langgraph_agent_runner.py` on a small subset of SPL IDs (`n=5`).

This notebook intentionally stops after `aggregated_rows` and does **not** run evaluation.

In [2]:
import os,torch
os.environ["RUNNER_CUDA_VISIBLE_DEVICES"] = "2"
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
print(os.environ.get("CUDA_VISIBLE_DEVICES"))
print(torch.cuda.device_count())

2
1

In [ ]:
!nvidia-smi

In [ ]:
from VaxMapper.src.llm import load_model_local,build_message
from VaxMapper.src.utils.llm_prompt import CONTRA_EXTRACT_SYSTEM_PROMPT, CONTRA_EXTRACT_USER_PROMPT

In [ ]:
from langgraph.graph import END, StateGraph

In [ ]:
model_id = "google/gemma-4-31B-it"

In [ ]:
# tok = AutoTokenizer.from_pretrained(model_id,trust_remote_code=True)

In [ ]:
# model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto")

In [ ]:
model = load_model_local(model_id=model_id, device_map="auto")

In [ ]:
generation_config = {
    "temperature": 0.1,         # Low for high precision
    "top_p": 0.8,               # Standard for instruct mode
    "top_k": 20,                # Recommended to prevent language drift
    "repetition_penalty": 1.05, # Prevent MoE looping
    "do_sample": True,          # Required for temperature/top_p/top_k
    "max_new_tokens": 4096,     # Space for clinical data
}

In [ ]:
system_prompt = CONTRA_EXTRACT_SYSTEM_PROMPT
user_prompt_template = CONTRA_EXTRACT_USER_PROMPT
from VaxMapper.src.utils.dailymed import CONTRA_Loinc, extract_section
from langgraph_agent_runner import load_spl_records_from_file
SPL_LIST_PATH = os.environ.get("SMOKETEST_SPL_LIST", "results/setid_100.txt")
N = 1
all_spl_records = load_spl_records_from_file(SPL_LIST_PATH)
spl_records = all_spl_records[:N]
spl = spl_records[0]
contra_section = extract_section(str(spl.get("SPL_SET_ID")), [CONTRA_Loinc])
result = (contra_section.get("sections")).get(CONTRA_Loinc, {})
contra_text = result.get("section_text")
contra_text

In [ ]:
messages = build_message(system_prompt, user_prompt_template.format(text=contra_text))

In [ ]:
model.generate(messages, **generation_config) 
#6m 7s (qwen 3.5)

In [ ]:
from VaxMapper.src.utils.snomed_utils import load_snomed_dataframes
snomed_frames = load_snomed_dataframes(snomed_source_dir="snomed_us_source")
ff = snomed_frames["snomed_complete_df"]

In [ ]:
ff

In [2]:
import json
import os
import time
from pathlib import Path

import pandas as pd
from IPython.display import JSON, display
from dotenv import load_dotenv
load_dotenv()

from langgraph_agent_runner import (
    AgentRunConfig,
    ContraLangGraphAgent,
    RunObserver,
    aggregate_agent_results,
    build_llm,
    load_spl_records_from_file,
)

/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import os
SPL_LIST_PATH = os.environ.get("SMOKETEST_SPL_LIST", "results/setid_100.txt")
N = 1
BACKEND = os.environ.get("LANGGRAPH_LLM_BACKEND", "huggingface")
MODELID = os.environ.get("HF_MODEL_ID")

print({
    "spl_list_path": SPL_LIST_PATH,
    "n": N,
    "backend": BACKEND,
    "model_id": MODELID,
    "output_dir": os.environ.get("OUTPUT_DIR"),
})

{'spl_list_path': 'results/setid_100.txt', 'n': 1, 'backend': 'huggingface', 'model_id': 'google/gemma-4-31B-it', 'output_dir': 'results/20260415'}

In [4]:
all_spl_records = load_spl_records_from_file(SPL_LIST_PATH)
spl_records = all_spl_records[:N]

# pd.DataFrame(spl_records)

In [5]:
config = AgentRunConfig.from_env()
config

AgentRunConfig(attribute_table={'causative_agent': 246075003, 'severity': 246112005, 'clinical_course': 263502005}, extraction_max_tokens=512, direct_match_max_tokens=56, route_or_fill_max_tokens=128, retries=2, recursion_limit=512, stop=['<<END_JSON>>'], use_strict_prompts=True)

In [ ]:
print(os.environ.get("CUDA_VISIBLE_DEVICES"))

In [ ]:
llm = build_llm(BACKEND)
observer = RunObserver(audit_enabled=False, progress_enabled=True)
config = AgentRunConfig.from_env()
agent = ContraLangGraphAgent(llm=llm, cfg=config, observer=observer)

In [ ]:
config

In [ ]:
result = agent.process_spl(spl_records[0])

In [ ]:
result

In [ ]:
(config.stop,
config.retries,
config.max_llm_tokens_mid,)

In [5]:
spl_records[0]

{'SPL_SET_ID': '083a3282-254f-4042-b0eb-70f76a279f10'}

In [9]:
from VaxMapper.src.utils.dailymed import CONTRA_Loinc, extract_section
spl = spl_records[0]
contra_section = extract_section(str(spl.get("SPL_SET_ID")), [CONTRA_Loinc])
result = (contra_section.get("sections")).get(CONTRA_Loinc, {})
contra_text = result.get("section_text")
contra_text

'Administration with nitrates and nitric oxide donors (2.4,\n\n4.1)\n\nAdministration with guanylate cyclase (GC) stimulators, such as riociguat (2.4,\n\n4.2)'

In [10]:
contra_section

{'setid': '083a3282-254f-4042-b0eb-70f76a279f10',
 'product_name': 'Vardenafil Hydrochloride',
 'found': True,
 'sections': {'34070-3': {'section_xml': '<section xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="S4">\n  <id root="8ab5f702-c2d9-430e-b33a-30c9d4798bab"/>\n  <code code="34070-3" codeSystem="2.16.840.1.113883.6.1" displayName="CONTRAINDICATIONS SECTION"/>\n  <title>4 CONTRAINDICATIONS</title>\n  <effectiveTime value="20161103"/>\n  <excerpt>\n    <highlight>\n      <text>\n        <list listType="unordered">\n          <item>Administration with nitrates and nitric oxide donors (\n          \n  \n     <linkHtml href="#S2.4">2.4</linkHtml>, \n          \n  \n     <linkHtml href="#S4.1">4.1</linkHtml>)\n         \n \n    </item>\n          <item>Administration with guanylate cyclase (GC) stimulators, such as riociguat (\n          \n  \n     <linkHtml href="#S2.4">2.4</linkHtml>, \n          \n  \n     <linkHtml href="#S4.2">4.2</linkHtml>)\n         \n \n    </item>\n        </list>\n      </text>\n    </highlight>\n  </excerpt>\n  <component>\n    <section ID="S4.1">\n      <id root="f172856c-9b68-4a8e-b1d7-1f1b568391e2"/>\n      <code code="42229-5" codeSystem="2.16.840.1.113883.6.1" displayName="SPL UNCLASSIFIED SECTION"/>\n      <title>4.1 Nitrates</title>\n      <text>\n        <paragraph>Administration of vardenafil hydrochloride tablets with nitrates (either regularly and/or intermittently) and nitric oxide donors is contraindicated \n         \n \n  <content styleCode="italics">[see \n          \n  \n   <linkHtml href="#S12.2">Clinical Pharmacology (12.2)</linkHtml>]\n         \n \n  </content>. Consistent with the effects of PDE5 inhibition on the nitric oxide/cyclic guanosine monophosphate pathway, PDE5 inhibitors, including vardenafil hydrochloride tablets, may potentiate the hypotensive effects of nitrates. A suitable time interval following dosing of vardenafil hydrochloride tablets for the safe administration of nitrates or nitric oxide donors has not been determined.\n        \n\n </paragraph>\n      </text>\n      <effectiveTime value="20161103"/>\n    </section>\n  </component>\n  <component>\n    <section ID="S4.2">\n      <id root="e2bfb9a5-4a20-44a6-9004-5120a9aa324c"/>\n      <code code="42229-5" codeSystem="2.16.840.1.113883.6.1" displayName="SPL UNCLASSIFIED SECTION"/>\n      <title>4.2 Guanylate Cyclase (GC) Stimulators</title>\n      <text>\n        <paragraph>\n          <content styleCode="xmChange">Do not use vardenafil hydrochloride tablets in patients who are using a GC stimulator, such as riociguat. PDE5 inhibitors, including vardenafil hydrochloride tablets may potentiate the hypotensive effects of GC stimulators.</content>\n        </paragraph>\n      </text>\n      <effectiveTime value="20161103"/>\n    </section>\n  </component>\n</section>\n',
   'section_text': 'Administration with nitrates and nitric oxide donors (2.4,\n\n4.1)\n\nAdministration with guanylate cyclase (GC) stimulators, such as riociguat (2.4,\n\n4.2)'}}}

In [ ]:
from VaxMapper.src.utils.dailymed import CONTRA_Loinc, extract_section
from VaxMapper.src.utils.llm_prompt import extract_contraindication_items

max_tokens = 2048
stop = ['<<END_JSON>>']
retries = 2
spl = spl_records[0]
contra_section = extract_section(str(spl.get("SPL_SET_ID")), [CONTRA_Loinc])
result = (contra_section.get("sections")).get(CONTRA_Loinc, {})
contra_text = result.get("section_text")
items, raw = extract_contraindication_items(
    llm.chat,
    contra_text,
    max_tokens=max_tokens,
    stop=stop,
    retries=retries,
)
print("items:", items)
print("raw:", raw)

In [ ]:
# # Things to check 
# 1. max new tokens, max_llm_tokens_mid where do they all connect to in the codebase? Are they being used correctly?
# 2. model kwargs - temp, top_p (qwen has rep and presence penalty, how can we add them as options in the config?)
# 3. does the langgraph agent keep anything in context ? - No. Only state_dict items as defined in the class

In [ ]:
run_rows = []
timings = []

for idx, spl in enumerate(spl_records, start=1):
    started = time.perf_counter()
    result = agent.process_spl(spl)
    elapsed_s = time.perf_counter() - started
    run_rows.append(result)
    timings.append({
        "row": idx,
        "SPL_SET_ID": result.get("SPL_SET_ID"),
        "product_name": result.get("product_name"),
        "contra_section_found": result.get("contra_section_found"),
        "n_items_in": result.get("n_items_in"),
        "n_items_out": result.get("n_items_out"),
        "elapsed_s": round(elapsed_s, 2),
    })

timings_df = pd.DataFrame(timings)
timings_df

In [ ]:
result

In [ ]:
import transformers
print(transformers.__version__)

In [ ]:
aggregated_rows, csv_rows = aggregate_agent_results(run_rows)

print({
    "n_run_rows": len(run_rows),
    "n_aggregated_rows": len(aggregated_rows),
    "n_csv_rows": len(csv_rows),
})

In [ ]:
summary_rows = []
for row in run_rows:
    status_counts = {}
    for item in row.get("results", []):
        status = item.get("status", "UNKNOWN")
        status_counts[status] = status_counts.get(status, 0) + 1
    summary_rows.append({
        "SPL_SET_ID": row.get("SPL_SET_ID"),
        "product_name": row.get("product_name"),
        "n_items_in": row.get("n_items_in"),
        "n_items_out": row.get("n_items_out"),
        **status_counts,
    })

summary_df = pd.DataFrame(summary_rows).fillna(0)
summary_df

In [ ]:
csv_df = pd.DataFrame(csv_rows)
csv_df

# medgemma 13
Administration with nitrates
Administration with nitric oxide donors
Administration with guanylate cyclase (GC) stimulators
Administration with riociguat
history of angioedema or hypersensitivity related to previous treatment with an angiotensin converting enzyme inhibitor
hypersensitivity related to previous treatment with an angiotensin converting enzyme inhibitor
hereditary or idiopathic angioedema
hereditary angioedema
idiopathic angioedema
co-administer aliskiren with Lisinopril in patients with diabetes
hypersensitivity to any components of the preparation
Known hypersensitivity to aripiprazole (4)
individuals who have shown hypersensitivity to any of its ingredients

# medgemma run 2 (12)
Administration with nitrates
Administration with nitric oxide donors
Administration with guanylate cyclase (GC) stimulators, such as riociguat
history of angioedema or hypersensitivity related to previous treatment with an angiotensin converting enzyme inhibitor
hypersensitivity related to previous treatment with an angiotensin converting enzyme inhibitor
hereditary or idiopathic angioedema
hereditary angioedema
idiopathic angioedema
Do not co-administer aliskiren with Lisinopril in patients with diabetes
history of hypersensitivity to any components of the preparation
Known hypersensitivity to aripiprazole (4)
hypersensitivity to any of its ingredients

In [ ]:
problem_rows = []
for row in run_rows:
    for item in row.get("results", []):
        expression = item.get("expression")
        selected_focus_id = item.get("selected_focus_id")
        if expression and isinstance(expression, str) and expression.startswith("N/A"):
            problem_rows.append({
                "SPL_SET_ID": row.get("SPL_SET_ID"),
                "item_index": item.get("item_index"),
                "status": item.get("status"),
                "query_text": item.get("query_text"),
                "selected_focus_id": selected_focus_id,
                "expression": expression,
            })

pd.DataFrame(problem_rows)

In [ ]:
if run_rows:
    display(JSON(run_rows[0], expanded=False))
    display(JSON(aggregated_rows[0], expanded=False))

In [4]:
# 2026-04-03

from agent_runner import (
    AGG_CSV_COLUMNS,
    END as END_MARKER,
    aggregate_agent_results,
    candidate_label_by_id,
    evaluate_aggregated_predictions,
    load_spl_records_from_file,
    parse_json_with_end_marker,
    validate_postcoord_with_mrcm,
    write_csv_rows,
    write_jsonl,
)

In [5]:
import json
# gold_csv = "results/contra_gold_100_2.csv"
gold_csv = "results/contra_gold_100_3.csv"
aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"

In [ ]:
from agent_runner import evaluate_aggregated_predictions
import json
# gold_csv = "results/contra_gold_100_2.csv"
gold_csv = "results/contra_gold_100_3.csv"
aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"
metrics = evaluate_aggregated_predictions(
    pred_csv=aggregated_csv,
    gold_csv=gold_csv,
    out_json=eval_json,
    out_details_csv=eval_details_csv,
    decoupled=True,
    min_pair_score=0.5
)
print(json.dumps(metrics, indent=2))
print(f"Wrote evaluation metrics to: {eval_json}")
print(f"Wrote evaluation details to: {eval_details_csv}")

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 4970.30it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
{
  "inputs": {
    "pred_csv": "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.5,
    "decoupled": true,
    "assignment_method": "hungarian"
  },
  "extraction_level": {
    "tp": 289,
    "fp": 28,
    "fn": 25,
    "precision": 0.9116719242902208,
    "recall": 0.9203821656050956,
    "f1": 0.9160063391442155
  },
  "contraindication_level": {
    "tp": 147,
    "fp": 142,
    "fn": 142,
    "precision": 0.5086505190311419,
    "recall": 0.5086505190311419,
    "f1": 0.5086505190311419
  },
  "concept_level": {
    "tp": 293,
    "fp": 152,
    "fn": 183,
    "precision": 0.6584269662921348,
    "recall": 0.615546218487395,
    "f1": 0.6362649294245386
  }
}
Wrote details: results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv
{
  "inputs": {
    "pred_csv": "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.5,
    "decoupled": true,
    "assignment_method": "hungarian"
  },
  "extraction_level": {
    "tp": 289,
    "fp": 28,
    "fn": 25,
    "precision": 0.9116719242902208,
    "recall": 0.9203821656050956,
    "f1": 0.9160063391442155
  },
  "contraindication_level": {
    "tp": 147,
    "fp": 142,
    "fn": 142,
    "precision": 0.5086505190311419,
    "recall": 0.5086505190311419,
    "f1": 0.5086505190311419
  },
  "concept_level": {
    "tp": 293,
    "fp": 152,
    "fn": 183,
    "precision": 0.6584269662921348,
    "recall": 0.615546218487395,
    "f1": 0.6362649294245386
  }
}
Wrote evaluation metrics to: results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json
Wrote evaluation details to: results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv

In [ ]:
BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L6-v2
Key                          | Status     | Details
-----------------------------+------------+--------
bert.embeddings.position_ids | UNEXPECTED |        

Notes:
- UNEXPECTED:   can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
# 2026-04-08 
# BM25 index fixes to fix candidate retrueval issues (single word concept missing)

In [19]:
from VaxMapper.src.utils.elastisearch_utils import bulk_index, create_index, get_es_client
from VaxMapper.src.utils.hyb_mapper import SNOMED_CT_SETTINGS, build_es_index
from VaxMapper.src.utils.search_utils import build_snomed_query, bm25_candidates
from VaxMapper.src.utils.snomed_utils import load_snomed_dataframes

In [ ]:
from VaxMapper.src.utils.snomed_utils import load_snomed_dataframes
snomed_source_dir = "snomed_us_source"
snomed_frames = load_snomed_dataframes(snomed_source_dir=snomed_source_dir)

In [20]:
es = get_es_client()
es.info()
# Returns a space-separated string of index names, then splits into a list
indices = es.cat.indices(h='index', s='index').split()
print(indices)

['rxnorm_bm25', 'snomed_ct_bm25', 'snomed_ct_es_index', 'snomed_ct_es_index_original', 'vo_bm25']

In [ ]:
def get_ancestor_path(concept_id, relationships_df, descriptions_df, max_depth=4, include_concept_id=False):
    path = []
    current = concept_id
    for _ in range(max_depth):
        parent = relationships_df[
            (relationships_df['sourceId'] == current) &
            (relationships_df['typeId'] == 116680003)
        ]['destinationId'].values
        if not len(parent):
            break
        current = parent[0]
        label = descriptions_df[
            descriptions_df['conceptId'] == current
        ]['term'].values[0]
        path.insert(0, label)
    return " → ".join(path)

In [34]:
get_ancestor_path(1269354002, snomed_rel_df, snomed_frames['snomed_complete_df'], max_depth=10)

'SNOMED CT Concept (SNOMED RT+CTV3) → Clinical finding (finding) → Propensity to adverse reaction (finding) → Propensity to adverse reactions to drug (finding)'

In [9]:
import networkx as nx

In [14]:
def get_all_ancestor_paths(concept_id, G, descriptions_df, max_depth=4):
    # BFS edges going "up" (child → parent direction)
    visited_edges = list(nx.bfs_edges(G, concept_id, depth_limit=max_depth))
    
    # Get all reachable ancestors within depth
    reachable = {v for _, v in visited_edges}
    
    # Get all simple paths to each ancestor
    all_paths = []
    for ancestor in reachable:
        for path in nx.all_simple_paths(G, concept_id, ancestor, cutoff=max_depth):
            labels = [
                descriptions_df[descriptions_df['conceptId'] == c]['term'].values[0]
                for c in path
            ]
            print(" → ".join(labels))
            all_paths.append(" → ".join(labels))
            # print(all_paths)
    return all_paths

In [12]:
IS_A = 116680003
G = nx.DiGraph()
is_a = snomed_rel_df[snomed_rel_df['typeId'] == IS_A]
G.add_edges_from(zip(is_a['sourceId'], is_a['destinationId']))  # child → parent

def get_longest_ancestor_path(concept_id, G, descriptions_df, max_depth=10):
    END = list(nx.bfs_edges(G, concept_id, depth_limit=max_depth))[-1][1]
    longest = max(nx.all_simple_paths(G, concept_id, END, cutoff=max_depth), key=len)
    return " → ".join([
        descriptions_df[descriptions_df['conceptId'] == c]['term'].values[0]
        for c in longest
    ])

In [13]:
def get_longest_ancestor_paths(
    concept_id: int,
    is_a_graph: nx.DiGraph,
    concept_meta_df: pd.DataFrame,
    max_depth: int = 10,
) -> str:
    """Return a '→'-joined chain from concept to its most distant IS-A ancestor.

    Uses BFS distance to locate the deepest reachable ancestor within max_depth,
    then returns the single shortest path (= the unique BFS path) to that node.
    Avoids nx.all_simple_paths to prevent exponential blowup on dense hierarchies.
    """
    if concept_id not in is_a_graph:
        return _concept_term(concept_id, concept_meta_df)
    path_lengths = nx.single_source_shortest_path_length(
        is_a_graph, concept_id, cutoff=max_depth
    )
    if len(path_lengths) <= 1:
        return _concept_term(concept_id, concept_meta_df)
    deepest = max(path_lengths, key=path_lengths.get)
    path = nx.shortest_path(is_a_graph, concept_id, deepest)
    return " → ".join(_concept_term(c, concept_meta_df) for c in path)


def _concept_term(concept_id: int, concept_meta_df: pd.DataFrame) -> str:
    """O(1) label lookup from indexed concept_meta_df."""
    try:
        return str(concept_meta_df.at[concept_id, "term"])
    except KeyError:
        return str(concept_id)

In [14]:
get_longest_ancestor_paths(1269354002, G, snomed_frames['snomed_complete_df'], max_depth=10)

'Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'

In [6]:
snomed_frames['snomed_complete_df'].set_index('conceptId', inplace=True)

In [7]:
snomed_frames['snomed_complete_df'].at[1269354002, "term"]

'Hypersensitivity to erythromycin (finding)'

In [49]:
_concept_term(1269354002, snomed_frames['snomed_complete_df'])

'1269354002'

In [45]:
get_longest_ancestor_path(1269354002, G, snomed_frames['snomed_complete_df'], max_depth=10)

'Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'

In [30]:
root = G.graph.get('root')
root

In [21]:
xx = get_all_ancestor_paths(1269354002, G, snomed_frames['snomed_complete_df'], max_depth=5)

Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Hypersensitivity condition (finding)
Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding)
Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding)
Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)
Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)

In [20]:
xx

['Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Hypersensitivity condition (finding)',
 'Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding)',
 'Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding)',
 'Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding)',
 'Hypersensitivity to erythromycin (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding)']

In [23]:
longest = max(nx.all_simple_paths(G,293619005, 138875005), key=len)
print(" → ".join([snomed_frames['snomed_complete_df'][snomed_frames['snomed_complete_df']['conceptId'] == c]['term'].values[0] for c in longest]))

Allergy to ibuprofen (finding) → Allergy to non-steroidal anti-inflammatory agent (finding) → Allergy to drug (finding) → Allergic disposition (finding) → Allergic condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)

In [24]:
longest = max(nx.all_simple_paths(G,1269353008, 138875005), key=len)
print(" → ".join([snomed_frames['snomed_complete_df'][snomed_frames['snomed_complete_df']['conceptId'] == c]['term'].values[0] for c in longest]))

Hypersensitivity to gentamicin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)

In [25]:
longest = max(nx.all_simple_paths(G,218613000, 138875005), key=len)
print(" → ".join([snomed_frames['snomed_complete_df'][snomed_frames['snomed_complete_df']['conceptId'] == c]['term'].values[0] for c in longest]))

Adverse reaction caused by ibuprofen (disorder) → Non-steroidal anti-inflammatory drug adverse reaction (disorder) → Non-opioid analgesic adverse reaction (disorder) → Analgesic adverse reaction (disorder) → Adverse reaction caused by drug (disorder) → Adverse reaction (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)

In [26]:
longest = max(nx.all_simple_paths(G,1269400003, 138875005), key=len)
print(" → ".join([snomed_frames['snomed_complete_df'][snomed_frames['snomed_complete_df']['conceptId'] == c]['term'].values[0] for c in longest]))

Hypersensitivity to nalidixic acid (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)

In [43]:
visited_edges = list(nx.bfs_edges(G, 1269354002, depth_limit=10))
visited_edges

[(1269354002, 419511003),
 (1269354002, 609433001),
 (419511003, 420134006),
 (609433001, 473010000),
 (420134006, 404684003),
 (404684003, 138875005)]

In [44]:
reachable = {v for _, v in visited_edges}
reachable

{138875005, 404684003, 419511003, 420134006, 473010000, 609433001}

In [46]:
list(nx.all_simple_paths(G, 1269354002, 138875005, cutoff=10))

[[1269354002, 419511003, 420134006, 404684003, 138875005],
 [1269354002, 609433001, 420134006, 404684003, 138875005],
 [1269354002, 609433001, 473010000, 404684003, 138875005]]

In [15]:
get_ancestor_path(1269354002, snomed_rel_df, snomed_frames["snomed_complete_df"], max_depth=10)

NameError: name 'get_ancestor_path' is not defined

In [18]:
SNOMED_CT_SETTINGS

{'settings': {'index': {'number_of_shards': 1,
   'number_of_replicas': 1,
   'similarity': {'default': {'type': 'BM25', 'k1': 1.2, 'b': 0.5}}},
  'analysis': {'filter': {'snomed_shingle:': {'type': 'shingle',
     'min_shingle_size': 2,
     'max_shingle_size': 3,
     'output_unigrams': True}},
   'analyzer': {'snomed_text': {'type': 'custom',
     'tokenizer': 'standard',
     'filter': ['lowercase', 'asciifolding']},
    'snomed_text_shingle': {'type': 'custom',
     'tokenizer': 'standard',
     'filter': ['lowercase', 'asciifolding', 'snomed_shingle:']}}}},
 'mappings': {'properties': {'conceptId': {'type': 'keyword'},
   'preferredTerm': {'type': 'text',
    'analyzer': 'snomed_text',
    'search_analyzer': 'snomed_text',
    'copy_to': ['all_terms'],
    'fields': {'exact': {'type': 'keyword'},
     'phrase': {'type': 'text',
      'analyzer': 'snomed_text',
      'index_options': 'offsets'},
     'shingle': {'type': 'text', 'analyzer': 'snomed_text_shingle'}}},
   'synonyms': {'type': 'text',
    'analyzer': 'snomed_text',
    'search_analyzer': 'snomed_text',
    'copy_to': ['all_terms']},
   'all_terms': {'type': 'text',
    'analyzer': 'snomed_text',
    'search_analyzer': 'snomed_text'},
   'semantic_tag': {'type': 'keyword'}}}}

In [5]:
es_index= "snomed_ct_bm25"
build_es_index(es,es_index,snomed_frames["snomed_complete_df"],rebuild_index=True, index_settings=SNOMED_CT_SETTINGS)

Deleting existing index: snomed_ct_bm25
Creating index 'snomed_ct_bm25'...

In [19]:
es.info()

ObjectApiResponse({'name': 'msdplaplp001.uth.tmc.edu', 'cluster_name': 'elasticsearch', 'cluster_uuid': 'm4zPSJyjTKCUH2PiE0ADfw', 'version': {'number': '9.0.0', 'build_flavor': 'default', 'build_type': 'tar', 'build_hash': '112859b85d50de2a7e63f73c8fc70b99eea24291', 'build_date': '2025-04-08T15:13:46.049795831Z', 'build_snapshot': False, 'lucene_version': '10.1.0', 'minimum_wire_compatibility_version': '8.18.0', 'minimum_index_compatibility_version': '8.0.0'}, 'tagline': 'You Know, for Search'})

In [20]:
es_index = 'snomed_ct_es_index'
# 'snomed_ct_es_index_original

In [ ]:
settings = es.indices.get_settings(index="snomed_ct_es_index")
print(settings)

{'snomed_ct_es_index': {'settings': {'index': {'routing': {'allocation': {'include': {'_tier_preference': 'data_content'}}}, 'number_of_shards': '1', 'provided_name': 'snomed_ct_es_index', 'similarity': {'default': {'type': 'BM25', 'b': '0.5', 'k1': '1.2'}}, 'creation_date': '1776198453404', 'analysis': {'filter': {'snomed_shingle:': {'max_shingle_size': '3', 'min_shingle_size': '2', 'output_unigrams': 'true', 'type': 'shingle'}}, 'analyzer': {'snomed_text_shingle': {'filter': ['lowercase', 'asciifolding', 'snomed_shingle:'], 'type': 'custom', 'tokenizer': 'standard'}, 'snomed_text': {'filter': ['lowercase', 'asciifolding'], 'type': 'custom', 'tokenizer': 'standard'}}}, 'number_of_replicas': '1', 'uuid': 'dug0fIVpQ9eHyCFz_ERREg', 'version': {'created': '9009000'}}}}}

In [22]:
settings = es.indices.get_settings(index="snomed_ct_es_index_original")
print(settings)

{'snomed_ct_es_index_original': {'settings': {'index': {'routing': {'allocation': {'include': {'_tier_preference': 'data_content'}}}, 'number_of_shards': '1', 'provided_name': 'snomed_ct_es_index_original', 'similarity': {'default': {'type': 'BM25', 'b': '0.75', 'k1': '1.2'}}, 'creation_date': '1776185692830', 'analysis': {'filter': {'snomed_shingle:': {'max_shingle_size': '3', 'min_shingle_size': '2', 'output_unigrams': 'true', 'type': 'shingle'}}, 'analyzer': {'snomed_text_shingle': {'filter': ['lowercase', 'asciifolding', 'snomed_shingle:'], 'type': 'custom', 'tokenizer': 'standard'}, 'snomed_text': {'filter': ['lowercase', 'asciifolding'], 'type': 'custom', 'tokenizer': 'standard'}}}, 'number_of_replicas': '1', 'uuid': 'N1Ms1NFVTtKLA2Rz93j1CA', 'version': {'created': '9009000'}}}}}

In [8]:
mappings = es.indices.get_mapping(index=es_index)
print(mappings)

{'snomed_ct_bm25': {'mappings': {'properties': {'all_terms': {'type': 'text', 'analyzer': 'snomed_text'}, 'conceptId': {'type': 'keyword'}, 'preferredTerm': {'type': 'text', 'fields': {'exact': {'type': 'keyword'}, 'phrase': {'type': 'text', 'index_options': 'offsets', 'analyzer': 'snomed_text'}, 'shingle': {'type': 'text', 'analyzer': 'snomed_text_shingle'}}, 'copy_to': ['all_terms'], 'analyzer': 'snomed_text'}, 'semantic_tag': {'type': 'keyword'}, 'synonyms': {'type': 'text', 'copy_to': ['all_terms'], 'analyzer': 'snomed_text'}}}}}

In [33]:
query_text = "Mycobacterial infection of the eye"
# Old call — still works, no changes needed
results = bm25_candidates(
    es=es, query_text=query_text, index="snomed_ct_es_index", k=50,
      text_field="all_terms", id_field="conceptId", label_field="preferredTerm")
[r['label'] for r in results]

['Mycobacterial infection of the central nervous system (disorder)',
 'Neonatal infection of the eye (disorder)',
 'Atypical mycobacterial infection of lung (disorder)',
 'Atypical mycobacterial infection of hand (disorder)',
 'Atypical mycobacterial infection (disorder)',
 'Disseminated atypical mycobacterial infection (disorder)',
 'Infection of tendon sheath caused by Mycobacterium (disorder)',
 'Keratitis of right eye caused by Mycobacterium (disorder)',
 'Keratitis of left eye caused by Mycobacterium (disorder)',
 'Mycobacterial infection (excluding tuberculosis AND leprosy) (disorder)',
 'Skin and soft tissue atypical mycobacterial infection (disorder)',
 'Mendelian susceptibility to mycobacterial disease (disorder)',
 'Susceptibility to viral and mycobacterial infection (disorder)',
 'Gonococcal infection of eye (disorder)',
 'Massaging of the eye (procedure)',
 'At increased risk for infection of eye (finding)',
 'Bacterial infection of the nervous system (disorder)',
 'Bacterial infection of the digestive tract (disorder)',
 'Viral infection of the digestive tract (disorder)',
 'Bacterial infection of eye (disorder)',
 'Infection of right eye (disorder)',
 'Infection of left eye (disorder)',
 'Inflammatory disorder of the eye (disorder)',
 'Malignant lymphoma of the eye region (disorder)',
 'Streptococcus group B infection of the infant (disorder)',
 'Brucella infection of the central nervous system (disorder)',
 'Chlamydial infection of the central nervous system (disorder)',
 'Coccidioides infection of the central nervous system (disorder)',
 'Coxsackievirus infection of the central nervous system (disorder)',
 'Cryptococcus infection of the central nervous system (disorder)',
 'Echovirus infection of the central nervous system (disorder)',
 'Ehrlichia infection of the central nervous system (disorder)',
 'Gonococcal infection of the central nervous system (disorder)',
 'Leptospira infection of the central nervous system (disorder)',
 'Listeria infection of the central nervous system (disorder)',
 'Streptococcus infection of the central nervous system (disorder)',
 'Haemophilus infection of the central nervous system (disorder)',
 'Arthritis following mycobacteriosis (disorder)',
 'Infection of the breast AND/OR nipple associated with childbirth (disorder)',
 'Fungal infection of eye (disorder)',
 'Infection of anterior chamber of eye caused by parasite (disorder)',
 'Disorders of prostheses and implants of the eye (disorder)',
 'Escherichia coli infection of the central nervous system (disorder)',
 'Herpes virus infection of the central nervous system (disorder)',
 'Mycobacteriosis (disorder)',
 'Gastrointestinal infection caused by non-tuberculous Mycobacterium (disorder)',
 'Eye infection (disorder)',
 'Recurrent herpes simplex infection of eye (disorder)',
 'Epstein-Barr virus infection of the retina (disorder)',
 'Infection of transplanted cornea of right eye (disorder)']

In [ ]:
from VaxMapper.src.utils.snomed_utils import load_snomed_dataframes
snomed_source_dir = "snomed_us_source"
snomed_frames = load_snomed_dataframes(snomed_source_dir=snomed_source_dir)

In [6]:
from VaxMapper.src.utils.search_utils import search_query

/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

In [8]:
import torch

if torch.cuda.is_available():
    print(f"Number of visible GPUs: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("No CUDA GPUs available.")

Number of visible GPUs: 1
GPU 0: NVIDIA A100-SXM4-80GB

In [11]:

# from sentence_transformers import CrossEncoder
model_name = "google/embeddinggemma-300m"
# reranker_model_id = "cross-encoder/ms-marco-MiniLM-L6-v2"
device="cuda:0"
dense_index_path_old = "FAISS/embeddinggemma-300m.bin"
dense_index_path_new = "FAISS/enriched_embeddinggemma-300m.bin"
# st_model = load_ST_model(model_name, device="cuda:0")
# cross_encoder = CrossEncoder(reranker_model_id, device="cuda:0")

In [5]:
import pandas as pd
from typing import Optional, Sequence, Set, Dict, List
ISA = 116680003
from collections import defaultdict
import re
def create_enriched_terms_df(
    snomed_complete_df: pd.DataFrame,
    rel_df: pd.DataFrame,
    exclude_type_ids: Optional[Set[int]] = None,
) -> pd.DataFrame:
    """
    Build one row per concept with a rich pipe-delimited embedding string.

    Format:
        preferred_term | syn1 | syn2 | ... | semantic_tag | attr_name1 = val1 | ...

    Columns returned:
        - conceptId  (int)
        - term_text  (str)
    """
    if exclude_type_ids is None:
        exclude_type_ids = {int(ISA)}  # always exclude IS-A

    # Build a fast lookup: conceptId -> preferred term (stripped of semantic tag)
    id_to_term: Dict[int, str] = {}
    for _, row in snomed_complete_df.iterrows():
        cid = int(row["conceptId"])
        # Strip semantic tag from preferred term for attribute names/values
        id_to_term[cid] = re.sub(r"\s*\([^)]+\)\s*$", "", str(row["term"])).strip()

    # Filter relationships: active, non-excluded types only
    attr_df = rel_df[~rel_df["typeId"].isin(exclude_type_ids)].copy()

    # Group attributes per source concept
    attr_map: Dict[int, List[str]] = defaultdict(list)
    for _, row in attr_df.iterrows():
        src = int(row["sourceId"])
        type_name = id_to_term.get(int(row["typeId"]), str(row["typeId"]))
        dest_name = id_to_term.get(int(row["destinationId"]), str(row["destinationId"]))
        attr_map[src].append(f"{type_name} = {dest_name}")

    rows = []
    for _, row in snomed_complete_df.iterrows():
        cid = int(row["conceptId"])
        parts = [str(row["term"])]                          # preferred term (with tag)
        synonyms = row.get("synonyms") or []
        parts.extend(str(s) for s in synonyms if s)        # all synonyms
        parts.append(str(row.get("semantic_tag", "")))      # semantic tag
        parts.extend(attr_map.get(cid, []))                 # attribute = value pairs
        term_text = " | ".join(p for p in parts if p)
        rows.append({"conceptId": cid, "term_text": term_text})

    return pd.DataFrame(rows)

In [9]:
en_terms_df = create_enriched_terms_df(
    snomed_complete_df=snomed_frames["snomed_complete_df"],
    rel_df=snomed_frames["rel_df"],
    exclude_type_ids={ISA},  # only exclude IS-A for embeddings
)
en_terms_df.head()

   conceptId                                          term_text
0  127362006  Previous pregnancies (finding) | Previous preg...
1  125587004  Superficial injury (disorder) | Superficial in...
2  125643001  Open wound (disorder) | Open wound | Open woun...
3  125665001  Crushing injury (disorder) | Crushing injury |...
4  125666000  Burn (disorder) | Burn | disorder | Associated...

In [12]:
from VaxMapper.src.utils.hyb_mapper import build_or_load_faiss_index
st_model, faiss_index_old = build_or_load_faiss_index(
        terms_df=snomed_frames["terms_df"],
        model_name=model_name,
        device=device,
        index_path=dense_index_path_old,
        rebuild_index=False,
    )

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 5459.00it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Moving FAISS index to GPU (first visible device, FAISS device 0)...
Index moved to GPU successfully.

In [13]:
st_model, faiss_index_new = build_or_load_faiss_index(
        terms_df=en_terms_df,
        model_name=model_name,
        device=device,
        index_path=dense_index_path_new,
        rebuild_index=False,
    )

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 5851.07it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Moving FAISS index to GPU (first visible device, FAISS device 0)...
Index moved to GPU successfully.

In [14]:
concept_meta_df = snomed_frames["concept_df"].set_index("conceptId")

In [98]:
query_text_original = "Mycobacterial infection of the eye"
query_text_serialized = "Mycobacterial infection of the eye | Pathological process = infectious process | Causative agent = Mycobacterium | Finding site = eye"

In [28]:
query_text_serialized = "Urticaria after taking NSAIDs| pathological process =Urticaria  substance_text=NSAID"

In [29]:
res = search_query(query_text=query_text_serialized,model=st_model,faiss_index=faiss_index_old,concept_meta_df=concept_meta_df,es=es,label_column="term",bm25_index="snomed_ct_es_index",bm25_text_field="preferredTerm",bm25_id_field="conceptId",bm25_label_field="preferredTerm",k_bm25=50,k_dense=50,k_final=25,n_final=15,
# cross_encoder=cross_encoder,
)
print(f"Final candidates: {[(r['label']) for r in res]}")

Final candidates: ['Non-steroid anti-inflammatory drug-induced angioedema-urticaria (disorder)', 'Urticaria medicamentosa (disorder)', 'Idiopathic urticaria (disorder)', 'Drug-aggravated angioedema-urticaria (disorder)', 'Allergic reaction caused by nonsteroidal antiinflammatory agent (disorder)', 'Bullous urticaria (disorder)', 'Allergy to non-steroidal anti-inflammatory agent (finding)', 'Photoallergic contact dermatitis due to non-steroidal anti-inflammatory drug (disorder)', 'Pressure urticaria (disorder)', 'Analgesics and non-steroidal anti-inflammatory drug allergy (navigational concept)', 'Urticaria (disorder)', 'Anaphylaxis caused by non-steroidal anti-inflammatory agent (disorder)', 'Episodic urticaria (disorder)', 'Non-allergic hypersensitivity to non-steroidal anti-inflammatory agent (finding)', 'Solar urticaria (disorder)']

In [30]:
res = search_query(query_text=query_text_serialized,model=st_model,faiss_index=faiss_index_new,concept_meta_df=concept_meta_df,es=es,label_column="term",bm25_index="snomed_ct_es_index_original",bm25_text_field="preferredTerm",bm25_id_field="conceptId",bm25_label_field="preferredTerm",k_bm25=50,k_dense=50,k_final=25,n_final=15,# cross_encoder=cross_encoder,
                   )
print(f"Final candidates: {[(r['label']) for r in res]}")

Final candidates: ['Urticaria medicamentosa (disorder)', 'Idiopathic urticaria (disorder)', 'Allergic urticaria (disorder)', 'Anaphylactic urticaria (disorder)', 'Non-steroid anti-inflammatory drug-induced angioedema-urticaria (disorder)', 'Urticaria (disorder)', 'Allergic reaction caused by nonsteroidal antiinflammatory agent (disorder)', 'Bullous urticaria (disorder)', 'Allergy to non-steroidal anti-inflammatory agent (finding)', 'Episodic urticaria (disorder)', 'Anaphylaxis caused by non-steroidal anti-inflammatory agent (disorder)', 'Pressure urticaria (disorder)', 'Non-allergic anaphylaxis caused by non steroidal anti-inflammatory drug (disorder)', 'Chronic urticaria (disorder)', 'Non-allergic hypersensitivity to non-steroidal anti-inflammatory agent (finding)']

In [34]:
# New call — uses multi-tier query
custom_query = build_snomed_query(
    query_text,
    text_field="preferredTerm",
    # semantic_tags=["disorder", "finding"],  # optional, pass None to skip
    semantic_tags=None 
)
results_new = bm25_candidates(
    es,
    query_text,
    index="snomed_ct_es_index",
    k=50,
    id_field="conceptId",
    label_field="preferredTerm",
    custom_query=custom_query,
)
[r['label'] for r in results_new]

['Mycobacterial infection of the central nervous system (disorder)',
 'Neonatal infection of the eye (disorder)',
 'Atypical mycobacterial infection of lung (disorder)',
 'Atypical mycobacterial infection of hand (disorder)',
 'Atypical mycobacterial infection (disorder)',
 'Disseminated atypical mycobacterial infection (disorder)',
 'Mycobacterial infection (excluding tuberculosis AND leprosy) (disorder)',
 'Susceptibility to viral and mycobacterial infection (disorder)',
 'Skin and soft tissue atypical mycobacterial infection (disorder)',
 'Massaging of the eye (procedure)',
 'Bacterial infection of the nervous system (disorder)',
 'Bacterial infection of the digestive tract (disorder)',
 'Viral infection of the digestive tract (disorder)',
 'Streptococcus group B infection of the infant (disorder)',
 'Brucella infection of the central nervous system (disorder)',
 'Chlamydial infection of the central nervous system (disorder)',
 'Coccidioides infection of the central nervous system (disorder)',
 'Coxsackievirus infection of the central nervous system (disorder)',
 'Cryptococcus infection of the central nervous system (disorder)',
 'Echovirus infection of the central nervous system (disorder)',
 'Ehrlichia infection of the central nervous system (disorder)',
 'Gonococcal infection of the central nervous system (disorder)',
 'Leptospira infection of the central nervous system (disorder)',
 'Listeria infection of the central nervous system (disorder)',
 'Streptococcus infection of the central nervous system (disorder)',
 'Haemophilus infection of the central nervous system (disorder)',
 'Inflammatory disorder of the eye (disorder)',
 'Epstein-Barr virus infection of the retina (disorder)',
 'Malignant lymphoma of the eye region (disorder)',
 'Escherichia coli infection of the central nervous system (disorder)',
 'Herpes virus infection of the central nervous system (disorder)',
 'Epstein Barr virus infection of the central nervous system (disorder)',
 'Infection of the breast AND/OR nipple associated with childbirth (disorder)',
 'Disorders of prostheses and implants of the eye (disorder)',
 'Infection of the penile urethra caused by Neisseria gonorrhoeae (disorder)',
 'Gonococcal infection of eye (disorder)',
 'Streptococcus group B infection of the infant - age less than 30 days (disorder)',
 'Bacterial infection of eye (disorder)',
 'Infection of right eye (disorder)',
 'Infection of left eye (disorder)',
 'Retained nonmagnetic foreign body in multiple sites of the eye (disorder)',
 'Fungal infection of eye (disorder)',
 'Infection of conjunctiva of left eye (disorder)',
 'Infection of conjunctiva of right eye (disorder)',
 'At increased risk for infection of eye (finding)',
 'Infection of transplanted cornea of right eye (disorder)',
 'Infection of transplanted cornea of left eye (disorder)',
 'Recurrent herpes simplex infection of eye (disorder)',
 'Infection of anterior chamber of eye caused by parasite (disorder)',
 'Infection of eye caused by Borrelia (disorder)']

In [30]:
custom_query

{'bool': {'should': [{'term': {'preferredTerm.exact': {'value': 'mycobacterial infection of the eye',
      'boost': 5.0}}},
   {'match_phrase': {'preferredTerm.phrase': {'query': 'Mycobacterial infection of the eye',
      'boost': 3.0}}},
   {'match': {'preferredTerm.shingle': {'query': 'Mycobacterial infection of the eye',
      'boost': 2.0}}},
   {'match': {'all_terms': {'query': 'Mycobacterial infection of the eye',
      'operator': 'or',
      'boost': 0.6}}}],
  'minimum_should_match': 1}}

In [22]:
from VaxMapper.src.utils.hyb_mapper import (
    DEFAULT_ITEM_TERM_KEYS,
    get_cached_mapper_resources,
    retrieve_candidates_for_item as retrieve_candidates_for_item_hybrid,
    map_item_terms
)

In [17]:
from langgraph_agent_runner import retrieve_candidates_for_item
import os

In [18]:
resources = get_cached_mapper_resources(
    snomed_source_dir=os.environ.get("SNOMED_SOURCE_DIR", "snomed_us_source"),
    concept_path=os.environ.get("SNOMED_CONCEPT_PATH"),
    description_path=os.environ.get("SNOMED_DESCRIPTION_PATH"),
    es_index=os.environ.get("MAPPER_ES_INDEX", "snomed_ct_es_index"),
    dense_index_path=os.environ.get("MAPPER_DENSE_INDEX_PATH", "results/snomed_terms_dense_test.bin"),
    model_name=os.environ.get("MAPPER_MODEL_NAME", "tavakolih/all-MiniLM-L6-v2-pubmed-full"),
    device=os.environ.get("MAPPER_DEVICE", "cuda:0"),
    k_dense=int(os.environ.get("MAPPER_K_DENSE", "50")),
    k_bm25=int(os.environ.get("MAPPER_K_BM25", "50")),
    k_final=int(os.environ.get("MAPPER_K_FINAL", "20")),
    rebuild_dense_index=os.environ.get("MAPPER_REBUILD_DENSE_INDEX", "").lower() in {"1", "true", "yes"},
    rebuild_es_index=os.environ.get("MAPPER_REBUILD_ES_INDEX", "").lower() in {"1", "true", "yes"},
    item_term_keys=DEFAULT_ITEM_TERM_KEYS,
    reranker_model_id=os.environ.get("RERANKER_MODEL_ID", ""),
    reranker_device=os.environ.get("RERANKER_DEVICE", "cuda:0"),
)

Index 'snomed_ct_bm25' already exists; skipping creation.
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7629.45it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Moving FAISS index to GPU (first visible device, FAISS device 0)...
Index moved to GPU successfully.

In [25]:
type(resources)

VaxMapper.src.utils.hyb_mapper.MapperResources

In [65]:
snomed_frames.keys()

dict_keys(['concept_df', 'synonym_df', 'terms_df', 'snomed_complete_df', 'domain', 'attr_domain', 'attr_range', 'rel_df'])

In [63]:
snomed_frames["terms_df"]

                  conceptId                       term_text  term_type
0                 127362006  Previous pregnancies (finding)  preferred
1                 125587004   Superficial injury (disorder)  preferred
2                 125643001           Open wound (disorder)  preferred
3                 125665001      Crushing injury (disorder)  preferred
4                 125666000                 Burn (disorder)  preferred
...                     ...                             ...        ...
1017041  900000000000548007                       Preferred    synonym
1017042  900000000000549004                      Acceptable    synonym
1017043  900000000000550004                      Definition    synonym
1017044  625544171000132109    Disorder of pancreatic stent    synonym
1017045  933316181000036101                     Vorasidenib    synonym

[1017046 rows x 3 columns]

In [91]:
en_terms_df[en_terms_df["conceptId"]==15991511000119102]["term_text"].values[0]

'Chorioretinitis of right eye caused by Mycobacterium tuberculosis (disorder) | Chorioretinitis of right eye caused by Mycobacterium tuberculosis | Right chorioretinitis caused by Mycobacterium tuberculosis | disorder | Pathological process = Infectious process | Causative agent = Mycobacterium tuberculosis | Pathological process = Infectious process | Finding site = Structure of choroid of right eye | Finding site = Structure of retina of right eye | Causative agent = Mycobacterium tuberculosis | Associated morphology = Inflammatory morphology | Associated morphology = Inflammatory morphology'

In [23]:
item = {
    "SPL_SET_ID": "test_spl",
    "item_index": 0,
    "ci_text": "hypersensitivity disorder"}

In [24]:
retrieve_candidates_for_item_hybrid(item, resources)

{'focus_candidates': [{'id': 426760008,
   'label': 'Delayed hypersensitivity disorder (disorder)',
   'fused': 0.032266458495966696,
   'from': 'bm25,dense',
   'ancestor_path': 'Delayed hypersensitivity disorder (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 421961002,
   'label': 'Hypersensitivity reaction (disorder)',
   'fused': 0.030776515151515152,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 21626009,
   'label': 'Cutaneous hypersensitivity (disorder)',
   'fused': 0.03057889822595705,
   'from': 'bm25,dense',
   'ancestor_path': 'Cutaneous hypersensitivity (disorder) → Disorder of skin (disorder) → Disorder of skin and/or subcutaneous tissue (disorder) → Disorder of integument (disorder) → Disorder of body system (disorder)'},
  {'id': 422076005,
   'label': 'Immunoglobulin E-mediated allergic disorder (disorder)',
   'fused': 0.02946236559139785,
   'from': 'bm25,dense',
   'ancestor_path': 'Immunoglobulin E-mediated allergic disorder (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 29268000,
   'label': 'Contact hypersensitivity (disorder)',
   'fused': 0.029273504273504274,
   'from': 'bm25,dense',
   'ancestor_path': 'Contact hypersensitivity (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 252097006,
   'label': 'Hypersensitivity finding (finding)',
   'fused': 0.028083267871170464,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity finding (finding) → Evaluation finding (finding) → Procedure related finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 427640001,
   'label': 'Non-allergic drug hypersensitivity disorder (disorder)',
   'fused': 0.027783137179239824,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic drug hypersensitivity disorder (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 426065008,
   'label': 'Hypersensitivity disorder mediated by immune complex (disorder)',
   'fused': 0.026144907723855092,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity disorder mediated by immune complex (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 473010000,
   'label': 'Hypersensitivity condition (finding)',
   'fused': 0.026008827238335436,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 400195000,
   'label': 'Contact hypersensitivity reaction (disorder)',
   'fused': 0.02557875991581674,
   'from': 'bm25,dense',
   'ancestor_path': 'Contact hypersensitivity reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 735449006,
   'label': 'Hypersensitivity reaction caused by food (disorder)',
   'fused': 0.025563671006668783,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity reaction caused by food (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609433001,
   'label': 'Hypersensitivity disposition (finding)',
   'fused': 0.02490842490842491,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 735458004,
   'label': 'Multiple drug hypersensitivity syndrome (disorder)',
   'fused': 0.024250440917107582,
   'from': 'bm25,dense',
   'ancestor_path': 'Multiple drug hypersensitivity syndrome (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609405001,
   'label': 'Non-allergic hypersensitivity condition (finding)',
   'fused': 0.024201491487266073,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic hypersensitivity condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 13468005,
   'label': 'Sensitive dentin (disorder)',
   'fused': 0.02219512195121951,
   'from': 'bm25,dense',
   'ancestor_path': 'Sensitive dentin (disorder) → Disorder of hard tissues of teeth (disorder) → Tooth disorder (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Digestive system finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609396006,
   'label': 'Non-allergic hypersensitivity disposition (finding)',
   'fused': 0.021568627450980392,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic hypersensitivity disposition (finding) → Non-allergic hypersensitivity condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 60555002,
   'label': 'Hypersensitivity angiitis (disorder)',
   'fused': 0.021018062397372743,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity angiitis (disorder) → Vasculitis (disorder) → Inflammatory disorder of the cardiovascular system (disorder) → Disorder of cardiovascular system (disorder) → Cardiovascular finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 12263007,
   'label': 'Type 1 hypersensitivity response (disorder)',
   'fused': 0.02058174944870314,
   'from': 'bm25,dense',
   'ancestor_path': 'Type 1 hypersensitivity response (disorder) → Allergic reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609406000,
   'label': 'Non-allergic hypersensitivity reaction (disorder)',
   'fused': 0.01976246105919003,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic hypersensitivity reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 472963003,
   'label': 'Hypersensitivity process (qualifier value)',
   'fused': 0.01834862385321101,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity process (qualifier value) → Pathological process (qualifier value) → Process (qualifier value) → Qualifier value (qualifier value) → SNOMED CT Concept (SNOMED RT+CTV3)'}],
 'direct_candidates': [{'id': 426760008,
   'label': 'Delayed hypersensitivity disorder (disorder)',
   'fused': 0.032266458495966696,
   'from': 'bm25,dense',
   'ancestor_path': 'Delayed hypersensitivity disorder (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 421961002,
   'label': 'Hypersensitivity reaction (disorder)',
   'fused': 0.030776515151515152,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 21626009,
   'label': 'Cutaneous hypersensitivity (disorder)',
   'fused': 0.03057889822595705,
   'from': 'bm25,dense',
   'ancestor_path': 'Cutaneous hypersensitivity (disorder) → Disorder of skin (disorder) → Disorder of skin and/or subcutaneous tissue (disorder) → Disorder of integument (disorder) → Disorder of body system (disorder)'},
  {'id': 422076005,
   'label': 'Immunoglobulin E-mediated allergic disorder (disorder)',
   'fused': 0.02946236559139785,
   'from': 'bm25,dense',
   'ancestor_path': 'Immunoglobulin E-mediated allergic disorder (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 29268000,
   'label': 'Contact hypersensitivity (disorder)',
   'fused': 0.029273504273504274,
   'from': 'bm25,dense',
   'ancestor_path': 'Contact hypersensitivity (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 252097006,
   'label': 'Hypersensitivity finding (finding)',
   'fused': 0.028083267871170464,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity finding (finding) → Evaluation finding (finding) → Procedure related finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 427640001,
   'label': 'Non-allergic drug hypersensitivity disorder (disorder)',
   'fused': 0.027783137179239824,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic drug hypersensitivity disorder (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 426065008,
   'label': 'Hypersensitivity disorder mediated by immune complex (disorder)',
   'fused': 0.026144907723855092,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity disorder mediated by immune complex (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 473010000,
   'label': 'Hypersensitivity condition (finding)',
   'fused': 0.026008827238335436,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 400195000,
   'label': 'Contact hypersensitivity reaction (disorder)',
   'fused': 0.02557875991581674,
   'from': 'bm25,dense',
   'ancestor_path': 'Contact hypersensitivity reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 735449006,
   'label': 'Hypersensitivity reaction caused by food (disorder)',
   'fused': 0.025563671006668783,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity reaction caused by food (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609433001,
   'label': 'Hypersensitivity disposition (finding)',
   'fused': 0.02490842490842491,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 735458004,
   'label': 'Multiple drug hypersensitivity syndrome (disorder)',
   'fused': 0.024250440917107582,
   'from': 'bm25,dense',
   'ancestor_path': 'Multiple drug hypersensitivity syndrome (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609405001,
   'label': 'Non-allergic hypersensitivity condition (finding)',
   'fused': 0.024201491487266073,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic hypersensitivity condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 13468005,
   'label': 'Sensitive dentin (disorder)',
   'fused': 0.02219512195121951,
   'from': 'bm25,dense',
   'ancestor_path': 'Sensitive dentin (disorder) → Disorder of hard tissues of teeth (disorder) → Tooth disorder (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Digestive system finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609396006,
   'label': 'Non-allergic hypersensitivity disposition (finding)',
   'fused': 0.021568627450980392,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic hypersensitivity disposition (finding) → Non-allergic hypersensitivity condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 60555002,
   'label': 'Hypersensitivity angiitis (disorder)',
   'fused': 0.021018062397372743,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity angiitis (disorder) → Vasculitis (disorder) → Inflammatory disorder of the cardiovascular system (disorder) → Disorder of cardiovascular system (disorder) → Cardiovascular finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 12263007,
   'label': 'Type 1 hypersensitivity response (disorder)',
   'fused': 0.02058174944870314,
   'from': 'bm25,dense',
   'ancestor_path': 'Type 1 hypersensitivity response (disorder) → Allergic reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 609406000,
   'label': 'Non-allergic hypersensitivity reaction (disorder)',
   'fused': 0.01976246105919003,
   'from': 'bm25,dense',
   'ancestor_path': 'Non-allergic hypersensitivity reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
  {'id': 472963003,
   'label': 'Hypersensitivity process (qualifier value)',
   'fused': 0.01834862385321101,
   'from': 'bm25,dense',
   'ancestor_path': 'Hypersensitivity process (qualifier value) → Pathological process (qualifier value) → Process (qualifier value) → Qualifier value (qualifier value) → SNOMED CT Concept (SNOMED RT+CTV3)'}],
 'causative_agent_candidates': [],
 'severity_candidates': [],
 'clinical_course_candidates': [],
 'mapped_row': {'SPL_SET_ID': 'test_spl',
  'item_index': 0,
  'ci_text': 'hypersensitivity disorder',
  'ci_text_terms': [{'id': 426760008,
    'label': 'Delayed hypersensitivity disorder (disorder)',
    'fused': 0.032266458495966696,
    'from': 'bm25,dense',
    'ancestor_path': 'Delayed hypersensitivity disorder (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 421961002,
    'label': 'Hypersensitivity reaction (disorder)',
    'fused': 0.030776515151515152,
    'from': 'bm25,dense',
    'ancestor_path': 'Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 21626009,
    'label': 'Cutaneous hypersensitivity (disorder)',
    'fused': 0.03057889822595705,
    'from': 'bm25,dense',
    'ancestor_path': 'Cutaneous hypersensitivity (disorder) → Disorder of skin (disorder) → Disorder of skin and/or subcutaneous tissue (disorder) → Disorder of integument (disorder) → Disorder of body system (disorder)'},
   {'id': 422076005,
    'label': 'Immunoglobulin E-mediated allergic disorder (disorder)',
    'fused': 0.02946236559139785,
    'from': 'bm25,dense',
    'ancestor_path': 'Immunoglobulin E-mediated allergic disorder (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 29268000,
    'label': 'Contact hypersensitivity (disorder)',
    'fused': 0.029273504273504274,
    'from': 'bm25,dense',
    'ancestor_path': 'Contact hypersensitivity (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 252097006,
    'label': 'Hypersensitivity finding (finding)',
    'fused': 0.028083267871170464,
    'from': 'bm25,dense',
    'ancestor_path': 'Hypersensitivity finding (finding) → Evaluation finding (finding) → Procedure related finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 427640001,
    'label': 'Non-allergic drug hypersensitivity disorder (disorder)',
    'fused': 0.027783137179239824,
    'from': 'bm25,dense',
    'ancestor_path': 'Non-allergic drug hypersensitivity disorder (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 426065008,
    'label': 'Hypersensitivity disorder mediated by immune complex (disorder)',
    'fused': 0.026144907723855092,
    'from': 'bm25,dense',
    'ancestor_path': 'Hypersensitivity disorder mediated by immune complex (disorder) → Immune hypersensitivity disorder by mechanism (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 473010000,
    'label': 'Hypersensitivity condition (finding)',
    'fused': 0.026008827238335436,
    'from': 'bm25,dense',
    'ancestor_path': 'Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 400195000,
    'label': 'Contact hypersensitivity reaction (disorder)',
    'fused': 0.02557875991581674,
    'from': 'bm25,dense',
    'ancestor_path': 'Contact hypersensitivity reaction (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 735449006,
    'label': 'Hypersensitivity reaction caused by food (disorder)',
    'fused': 0.025563671006668783,
    'from': 'bm25,dense',
    'ancestor_path': 'Hypersensitivity reaction caused by food (disorder) → Hypersensitivity reaction (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 609433001,
    'label': 'Hypersensitivity disposition (finding)',
    'fused': 0.02490842490842491,
    'from': 'bm25,dense',
    'ancestor_path': 'Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 735458004,
    'label': 'Multiple drug hypersensitivity syndrome (disorder)',
    'fused': 0.024250440917107582,
    'from': 'bm25,dense',
    'ancestor_path': 'Multiple drug hypersensitivity syndrome (disorder) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 609405001,
    'label': 'Non-allergic hypersensitivity condition (finding)',
    'fused': 0.024201491487266073,
    'from': 'bm25,dense',
    'ancestor_path': 'Non-allergic hypersensitivity condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 13468005,
    'label': 'Sensitive dentin (disorder)',
    'fused': 0.02219512195121951,
    'from': 'bm25,dense',
    'ancestor_path': 'Sensitive dentin (disorder) → Disorder of hard tissues of teeth (disorder) → Tooth disorder (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Digestive system finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 609396006,
    'label': 'Non-allergic hypersensitivity disposition (finding)',
    'fused': 0.021568627450980392,
    'from': 'bm25,dense',
    'ancestor_path': 'Non-allergic hypersensitivity disposition (finding) → Non-allergic hypersensitivity condition (finding) → Hypersensitivity condition (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)'},
   {'id': 60555002,
    'label': 'Hypersensitivity angiitis (disorder)',
    'fused': 0.021018062397372743,
    'from': 'bm25,dense',

In [26]:
import json


def get_available_keys(audit_file, spl_set_id, item_index, call_name):
    """Return all keys present in the matching llm_call record.

    Matches on spl_set_id, item_index, and call_name.
    Returns an empty list if no matching record is found.
    """
    with open(audit_file) as f:
        for line in f:
            record = json.loads(line)
            if (
                record.get("event_type") == "llm_call"
                and record.get("spl_set_id") == spl_set_id
                and record.get("item_index") == item_index
                and record.get("call_name") == call_name
            ):
                return list(record.keys())
    return []


def get_values(audit_file, spl_set_id, item_index, call_name, keys):
    """Return a dict of {key: value} for the requested keys from the matching llm_call record.

    Matches on spl_set_id, item_index, and call_name.
    Returns an empty dict if no matching record is found.
    Keys absent from the record are returned with value None.
    """
    with open(audit_file) as f:
        for line in f:
            record = json.loads(line)
            if (
                record.get("event_type") == "llm_call"
                and record.get("spl_set_id") == spl_set_id
                and record.get("item_index") == item_index
                and record.get("call_name") == call_name
            ):
                return {k: record.get(k) for k in keys}
    return {}

### Improvement by prompt examples for Extraction Stage

In [ ]:
## 0.5 CI 0.6 concept F1 - Baseline
AUDIT = "results/20260406/runtime_audit.jsonl"
SET_ID = "2b470e48-c23c-4f5c-916a-d38d8518896b"

# SPL-level extraction call (item_index is None)
item_index = 0
call_name = "direct_match"
available = get_available_keys(AUDIT, SET_ID, item_index=item_index, call_name=call_name)
# print("available keys:", available)

vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["system_prompt"])
print("values:", vals)

# "parsed_output", "parse_success", "duration_s"

values: {'system_prompt': '\nYou are a strict biomedical terminology validator.\nYour role is to determine if a candidate is a LEXICAL and SEMANTIC identity match for the contraindication query.\n\nYour ONLY task:\n- Identify if a DIRECT MATCH exists among the provided candidates.\n- If a match exists, select exactly ONE candidate from the list.\n- Otherwise, return no match.\n\n--------------------\nDIRECT MATCH (STRICT)\n--------------------\nA candidate is a DIRECT MATCH only if it is an exact semantic equivalent. Do NOT bridge concepts even if they are clinically related.\n\n1) Lexical-Semantic Alignment:\n- The candidate must match the specificity and naming of the query.\n- Do NOT bridge concepts that use different primary terms even if they are clinically related.\n- If the query text and candidate label belong to different levels of the hierarchy, return no match.\n2) Temporal/Contextual Scope:\n- "Post-X" is NOT a match for "X".\n- "History of X" is NOT a match for "X".\n- If the query implies a state after an event and the candidate is only the event, return no match.\n3) Meaning Completeness:\n- Do NOT select a candidate that represents only part of the query.\n4) Semantic Type Guardrail:\n- If the query implies a condition/state, do NOT select a procedure concept unless the query explicitly describes a procedure.\n5) Hierarchical Granularity:\n- A match must exist at the same level of specificity as the query.\n- A broader parent or narrower child is NOT a direct match.\n\n--------------------\nCANDIDATE ELIGIBILITY FILTERS\n--------------------\nUnless the query explicitly describes a procedure or product, do NOT select candidates whose label indicates:\n- procedure\n- administration\n- vaccination\n- other overly broad parent concepts when the query is specific\n\n--------------------\nOUTPUT FORMAT\n--------------------\nReturn ONLY minified JSON followed immediately by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"direct_match":true/false,"selected_id":"<candidate id or N/A>","selected_term":"<candidate term or N/A>"}<<END_JSON>>\n\nRules:\n- If direct_match=true, selected_id MUST be from the candidate list.\n- If direct_match=false, selected_id and selected_term MUST be N/A.\n'}

values: {'user_prompt': 'QUERY:\n"Mycobacterial infection of the eye"\n\nCANDIDATES (choose from these only):\n1) 866083008 | Concept name: Infection of eyelid caused by Mycobacterium tuberculosis (disorder) | Score: 6.615\n2) 1163500007 | Concept name: Infection of eyelid caused by Mycobacterium leprae (disorder) | Score: 6.145\n3) 15693481000119109 | Concept name: Keratitis of bilateral eyes caused by Mycobacterium (disorder) | Score: 3.954\n4) 128984004 | Concept name: Bacterial infection of eye (disorder) | Score: 3.845\n5) 15693521000119109 | Concept name: Keratitis of left eye caused by Mycobacterium (disorder) | Score: 3.331\n6) 15693441000119104 | Concept name: Keratitis of right eye caused by Mycobacterium (disorder) | Score: 3.331\n7) 406594003 | Concept name: Mycobacterial infection of the central nervous system (disorder) | Score: 2.872\n8) 35876006 | Concept name: Gonococcal infection of eye (disorder) | Score: 2.826\n9) 111811007 | Concept name: Mycobacterial infection (excluding tuberculosis AND leprosy) (disorder) | Score: 1.997\n10) 31194008 | Concept name: Fungal infection of eye (disorder) | Score: 1.761\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

------------------------------------------
values: {'user_prompt': 'QUERY:\nMycobacterial infection of the eye\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=infection\nsubstance_text=Mycobacterial\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 128270001 | Concept name: Fetal infection (disorder) | Score: 1.938\n2) 63459005 | Concept name: Clinical infection (disorder) | Score: 1.891\n3) 275393007 | Concept name: Oral infection (disorder) | Score: 1.444\n4) 371568002 | Concept name: Anal infection (disorder) | Score: 1.267\n5) 312155003 | Concept name: Genital infection (disorder) | Score: 0.974\n6) 10443009 | Concept name: Localized infection (disorder) | Score: 0.844\n7) 76844004 | Concept name: Local infection of wound (disorder) | Score: 0.423\n8) 23513009 | Concept name: Herpesvirus infection (disorder) | Score: 0.031\n9) 260976002 | Concept name: Presence of infection (qualifier value) | Score: 0.027\n10) 186747009 | Concept name: Coronavirus infection (disorder) | Score: -0.089\n\nCAUSATIVE_AGENT_CANDIDATES:\n1) 716340006 | Concept name: Mycobacterium bacteremicum (organism) | Score: 6.224\n2) 785918006 | Concept name: Genus Mycobacteroides (organism) | Score: 5.408\n3) 243368001 | Concept name: Genus Mycobacterium (organism) | Score: 5.326\n4) 712909005 | Concept name: Mycobacterium vulneris (organism) | Score: 5.270\n5) 113861009 | Concept name: Mycobacterium tuberculosis (organism) | Score: 5.109\n6) 427768005 | Concept name: Mycobacterium kubicae (organism) | Score: 4.974\n7) 432888001 | Concept name: Mycobacterium phocaicum (organism) | Score: 4.917\n8) 1285313007 | Concept name: Order Mycobacteriales (organism) | Score: 4.792\n9) 70801007 | Concept name: Mycobacterium microti (organism) | Score: 4.649\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'N/A', 'selected_problem_id': '63459005', 'fills': {'causative_agent': '243368001', 'severity': 'N/A', 'clinical_course': 'N/A'}}}

In [ ]:
## 0.6 CI 0.7 concept F1 - Extraction Prompt Update with example
AUDIT_2 = "results/20260407/gemma4/runtime_audit.jsonl"
SET_ID = "2b470e48-c23c-4f5c-916a-d38d8518896b"

# SPL-level extraction call (item_index is None)
item_index = 0
call_name = "direct_match"
available = get_available_keys(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name)
# print("available keys:", available)

vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["system_prompt"])
print("values:", vals)

values: {'system_prompt': '\nYou are a strict biomedical terminology validator.\nYour role is to determine if a candidate is a LEXICAL and SEMANTIC identity match for the contraindication query.\n\nYour ONLY task:\n- Identify if a DIRECT MATCH exists among the provided candidates.\n- If a match exists, select exactly ONE candidate from the list.\n- Otherwise, return no match.\n\nWhen in doubt, return no match. A false negative here is recoverable; a false positive is not.\n\n--------------------\nDIRECT MATCH (STRICT)\n--------------------\nA candidate is a DIRECT MATCH only if its label is an exact lexical-semantic equivalent to the query — identical clinical meaning, identical ontological level, identical primary term.\n\n1) Primary Term Identity:\n- The root condition word used in the query MUST be the same root condition word in the candidate label.\n- Clinically related terms that are NOT interchangeable in SNOMED CT:\n    * "Hypersensitivity" ≠ "Allergy"  (Allergy is a subtype of Hypersensitivity — different concepts)\n    * "Hypersensitivity" ≠ "Sensitivity"\n    * "Disorder" ≠ "Finding"\n    * "Reaction" ≠ "Hypersensitivity"\n- If the query says "hypersensitivity to X" and the candidate says "allergy to X", return no match even if they seem clinically equivalent. They occupy different positions in the SNOMED CT hierarchy.\n\n2) Hierarchical Granularity — subtypes and supertypes are both wrong:\n- A narrower (more specific) concept is NOT a match: "Allergy to ibuprofen" is NOT a match for "Hypersensitivity to ibuprofen".\n- A broader (more general) concept is NOT a match: "Hypersensitivity disorder" is NOT a match for "Hypersensitivity to ibuprofen".\n- The candidate must encode exactly the same meaning — not more specific, not more general.\n\n3) Meaning Completeness:\n- Do NOT select a candidate that represents only part of the query meaning.\n- Do NOT select a candidate that adds qualifiers not present in the query (e.g., "known", "documented", "acute").\n\n4) Temporal/Contextual Scope:\n- "Post-X" is NOT a match for "X".\n- "History of X" is NOT a match for "X".\n- If the query implies a state after an event and the candidate is only the event, return no match.\n\n5) Semantic Type Guardrail:\n- If the query implies a condition/state, do NOT select a procedure concept unless the query explicitly describes a procedure.\n\n--------------------\nCANDIDATE ELIGIBILITY FILTERS\n--------------------\nUnless the query explicitly describes a procedure or product, do NOT select candidates whose label indicates:\n- procedure\n- administration\n- vaccination\n- other overly broad parent concepts when the query is specific\n\n--------------------\nOUTPUT FORMAT\n--------------------\nReturn ONLY minified JSON followed immediately by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"direct_match":true/false,"selected_id":"<candidate id or N/A>","selected_term":"<candidate term or N/A>"}<<END_JSON>>\n\nRules:\n- If direct_match=true, selected_id MUST be from the candidate list.\n- If direct_match=false, selected_id and selected_term MUST be N/A.\n'}

### Improvement by BM25 tuning

In [34]:
## 0.6 CI 0.7 concept F1 - Extraction Prompt Update with example
AUDIT_2 = "results/20260407/gemma4/runtime_audit.jsonl"
SET_ID = "2b470e48-c23c-4f5c-916a-d38d8518896b"

# SPL-level extraction call (item_index is None)
item_index = 6
call_name = "direct_match"
available = get_available_keys(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name)
# print("available keys:", available)

vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("values:", vals)

values: {'user_prompt': 'QUERY:\n"allergic-type reactions after taking other NSAIDs"\n\nCANDIDATES (choose from these only):\n1) 293610009 |Allergy to non-steroidal anti-inflammatory agent (finding)|\n2) 871931002 |Allergic reaction after allergen immunotherapy (disorder)|\n3) 15920041000119105 |Allergic reaction caused by nonsteroidal antiinflammatory agent (disorder)|\n4) 386665002 |Pupil reactions normal (finding)|\n5) 293581006 |Analgesics and non-steroidal anti-inflammatory drug allergy (navigational concept)|\n6) 396079007 |Assessment of adverse drug reactions (procedure)|\n7) 781684006 |Non-allergic hypersensitivity to non-steroidal anti-inflammatory agent (finding)|\n8) 370899004 |Retention of foreign object in a patient after surgery or other procedure (event)|\n9) 293619005 |Allergy to ibuprofen (finding)|\n10) 419511003 |Propensity to adverse reactions to drug (finding)|\n', 'parsed_output': {'direct_match': True, 'selected_id': '15920041000119105', 'selected_term': 'Allergic reaction caused by nonsteroidal antiinflammatory agent (disorder)'}}

In [33]:
## 0.4 CI 0.6 concept F1 - Extraction Prompt Update with example + BM25 tuning
AUDIT_3 = "results/20260407/gemma4_bm25/runtime_audit.jsonl"
SET_ID = "2b470e48-c23c-4f5c-916a-d38d8518896b"

# SPL-level extraction call (item_index is None)
item_index = 6
call_name = "direct_match"
available = get_available_keys(AUDIT_3, SET_ID, item_index=item_index, call_name=call_name)
# print("available keys:", available)

vals = get_values(AUDIT_3, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("values:", vals)

values: {'user_prompt': 'QUERY:\n"allergic-type reactions after taking other NSAIDs"\n\nCANDIDATES (choose from these only):\n1) 293610009 |Allergy to non-steroidal anti-inflammatory agent (finding)|\n2) 15920041000119105 |Allergic reaction caused by nonsteroidal antiinflammatory agent (disorder)|\n3) 293581006 |Analgesics and non-steroidal anti-inflammatory drug allergy (navigational concept)|\n4) 781684006 |Non-allergic hypersensitivity to non-steroidal anti-inflammatory agent (finding)|\n5) 293619005 |Allergy to ibuprofen (finding)|\n6) 293625009 |Allergy to naproxen (finding)|\n7) 419901001 |Non-steroidal anti-inflammatory drug adverse reaction (disorder)|\n8) 15919911000119108 |Allergic reaction caused by analgesic (disorder)|\n9) 416093006 |Allergic reaction caused by drug (disorder)|\n10) 293584003 |Allergy to paracetamol (finding)|\n', 'parsed_output': {'direct_match': True, 'selected_id': '15920041000119105', 'selected_term': 'Allergic reaction caused by nonsteroidal antiinflammatory agent (disorder)'}}

In [38]:
## 0.6 CI 0.7 concept F1 - Extraction Prompt Update with example
AUDIT_2 = "results/20260407/gemma4/runtime_audit.jsonl"
## 0.4 CI 0.6 concept F1 - Extraction Prompt Update with example + BM25 tuning
AUDIT_3 = "results/20260407/gemma4_bm25/runtime_audit.jsonl"
SET_ID = "2b470e48-c23c-4f5c-916a-d38d8518896b"


item_index = 0
call_name = "route_or_fill"

for audit in [AUDIT_2, AUDIT_3]:
    vals = get_values(audit, SET_ID, item_index=item_index, call_name=call_name,
                      keys=["system_prompt","user_prompt","parsed_output"])
    print("values:", vals)
    print("\n\n")

values: {'system_prompt': '\nYou are a SNOMED CT minimal representation assistant for contraindications.\n\nYour job has two parts:\n1) Decide whether the contraindication can be sufficiently represented using ONLY:\n   - one focus concept\n   - optional causative_agent\n   - optional severity\n   - optional clinical_course\n2) Regardless of that decision, extract the best available minimal concept representation from the provided candidates.\n\nRules:\n- Always select the best focus concept you can from FOCUS_CANDIDATES, unless no credible focus exists.\n- Always select the best value for each attribute from its candidate list when supported by the text.\n- If no supported value exists for an attribute, output "N/A" for that attribute.\n- Use ONLY IDs from the provided candidate lists.\n- Do NOT invent IDs.\n\npost_decision rules:\n- "YES" if the contraindication is sufficiently represented by the minimal model above.\n- "N/A" if clinically important meaning remains outside that model, or if the representation is incomplete.\n\nOutput ONLY minified JSON followed by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"post_decision":"YES|N/A","selected_focus_id":"<id or N/A>","fills":{"causative_agent":"<id or N/A>","severity":"<id or N/A>","clinical_course":"<id or N/A>"}}<<END_JSON>>\n', 'user_prompt': 'QUERY:\nknown hypersensitivity to ibuprofen\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=hypersensitivity disorder\nsubstance_text=ibuprofen\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 426760008 |Delayed hypersensitivity disorder (disorder)|\n2) 421961002 |Hypersensitivity reaction (disorder)|\n3) 29268000 |Contact hypersensitivity (disorder)|\n4) 21626009 |Cutaneous hypersensitivity (disorder)|\n5) 252097006 |Hypersensitivity finding (finding)|\n6) 473010000 |Hypersensitivity condition (finding)|\n7) 427640001 |Non-allergic drug hypersensitivity disorder (disorder)|\n8) 609433001 |Hypersensitivity disposition (finding)|\n9) 400195000 |Contact hypersensitivity reaction (disorder)|\n10) 422076005 |Immunoglobulin E-mediated allergic disorder (disorder)|\n\nCAUSATIVE_AGENT_CANDIDATES:\n1) 387207008 |Ibuprofen (substance)|\n2) 725863000 |Ibuprofen sodium (substance)|\n3) 425516000 |Ibuprofen lysine (substance)|\n4) 725865007 |Ibuprofen sodium dihydrate (substance)|\n5) 38268001 |Product containing ibuprofen (medicinal product)|\n6) 776287003 |Product containing only ibuprofen (medicinal product)|\n7) 350321003 |Product containing ibuprofen in oral dose form (medicinal product form)|\n8) 329654002 |Product containing precisely ibuprofen 600 milligram/1 each conventional release oral tablet (clinical drug)|\n9) 779527000 |Product containing only ibuprofen in oral dose form (medicinal product form)|\n10) 370192006 |Product containing precisely ibuprofen 100 milligram/1 each conventional release oral tablet (clinical drug)|\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'YES', 'selected_focus_id': '421961002', 'fills': {'causative_agent': '387207008', 'severity': 'N/A', 'clinical_course': 'N/A'}}}



values: {'system_prompt': '\nYou are a SNOMED CT minimal representation assistant for contraindications.\n\nYour job has two parts:\n1) Decide whether the contraindication can be sufficiently represented using ONLY:\n   - one focus concept\n   - optional causative_agent\n   - optional severity\n   - optional clinical_course\n2) Regardless of that decision, extract the best available minimal concept representation from the provided candidates.\n\nRules:\n- Always select the best focus concept you can from FOCUS_CANDIDATES, unless no credible focus exists.\n- Always select the best value for each attribute from its candidate list when supported by the text.\n- If no supported value exists for an attribute, output "N/A" for that attribute.\n- Use ONLY IDs from the provided candidate lists.\n- Do NOT invent IDs.\n\npost_decision rules:\n- "YES" if the contraindication is sufficiently represented by the minimal model above.\n- "N/A" if clinically important meaning remains outside that model, or if the representation is incomplete.\n\nOutput ONLY minified JSON followed by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"post_decision":"YES|N/A","selected_focus_id":"<id or N/A>","fills":{"causative_agent":"<id or N/A>","severity":"<id or N/A>","clinical_course":"<id or N/A>"}}<<END_JSON>>\n', 'user_prompt': 'QUERY:\nknown hypersensitivity to ibuprofen\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=hypersensitivity disorder\nsubstance_text=ibuprofen\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 473010000 |Hypersensitivity condition (finding)|\n2) 422076005 |Immunoglobulin E-mediated allergic disorder (disorder)|\n3) 426760008 |Delayed hypersensitivity disorder (disorder)|\n4) 421961002 |Hypersensitivity reaction (disorder)|\n5) 609433001 |Hypersensitivity disposition (finding)|\n6) 85972008 |Sensory disorder (disorder)|\n7) 252097006 |Hypersensitivity finding (finding)|\n8) 21626009 |Cutaneous hypersensitivity (disorder)|\n9) 609405001 |Non-allergic hypersensitivity condition (finding)|\n10) 14151009 |Hyperesthesia (finding)|\n\nCAUSATIVE_AGENT_CANDIDATES:\n1) 387207008 |Ibuprofen (substance)|\n2) 725863000 |Ibuprofen sodium (substance)|\n3) 425516000 |Ibuprofen lysine (substance)|\n4) 725865007 |Ibuprofen sodium dihydrate (substance)|\n5) 418868002 |Dexibuprofen (substance)|\n6) 372665008 |Non-steroidal anti-inflammatory agent (substance)|\n7) 387517004 |Paracetamol (substance)|\n8) 108849007 |Suprofen (substance)|\n9) 38268001 |Product containing ibuprofen (medicinal product)|\n10) 1285524005 |Propacetamol (substance)|\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'YES', 'selected_focus_id': '473010000', 'fills': {'causative_agent': '387207008', 'severity': 'N/A', 'clinical_course': 'N/A'}}}

### Isolation Run - Issues between the enhanced and simple dense index

In [45]:
AUDIT_1 = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
AUDIT_2 = "results/20260415_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "6ae413ba-5a48-423f-8b8d-7a42661cf836"
item_index = 0
call_name = "direct_match"
print(f"Are system prompts identical? {get_values(AUDIT_1, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt') == get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt')}")
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Simple Dense Index:", vals,)
print("\n------------------------------------------")
vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Enhanced Dense Index:", vals)
# print("\n------------------------------------------")
# call_name = "route_or_fill"
# vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
#                   keys=["user_prompt","parsed_output"])
# print("values:", vals)

Are system prompts identical? True
Simple Dense Index: {'user_prompt': 'QUERY:\n"Known hypersensitivity to naproxen"\n\nCANDIDATES (choose from these only):\n1) 609534005 | Concept name: Non-allergic hypersensitivity to losartan (finding) | Score: -1.199 | Ancestor path: Non-allergic hypersensitivity to losartan (finding) → Non-allergic hypersensitivity to angiotensin II receptor antagonist (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n2) 218620007 | Concept name: Adverse reaction caused by naproxen (disorder) | Score: -1.312 | Ancestor path: Adverse reaction caused by naproxen (disorder) → Non-steroidal anti-inflammatory drug adverse reaction (disorder) → Non-opioid analgesic adverse reaction (disorder) → Analgesic adverse reaction (disorder) → Adverse reaction caused by drug (disorder) → Adverse reaction (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n3) 114931000119103 | Concept name: Hypersensitivity to abacavir (finding) | Score: -1.963 | Ancestor path: Hypersensitivity to abacavir (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n4) 1269353008 | Concept name: Hypersensitivity to gentamicin (finding) | Score: -1.974 | Ancestor path: Hypersensitivity to gentamicin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n5) 293625009 | Concept name: Allergy to naproxen (finding) | Score: -2.290 | Ancestor path: Allergy to naproxen (finding) → Allergy to non-steroidal anti-inflammatory agent (finding) → Allergy to drug (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n6) 609540003 | Concept name: Non-allergic hypersensitivity to enalapril (finding) | Score: -2.493 | Ancestor path: Non-allergic hypersensitivity to enalapril (finding) → Non-allergic hypersensitivity to angiotensin-converting enzyme inhibitor (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 1269354002 | Concept name: Hypersensitivity to erythromycin (finding) | Score: -2.611 | Ancestor path: Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 18361000122109 | Concept name: Non-allergic hypersensitivity to moexipril (finding) | Score: -2.613 | Ancestor path: Non-allergic hypersensitivity to moexipril (finding) → Non-allergic hypersensitivity to angiotensin-converting enzyme inhibitor (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n9) 609545008 | Concept name: Non-allergic hypersensitivity to ramipril (finding) | Score: -2.635 | Ancestor path: Non-allergic hypersensitivity to ramipril (finding) → Non-allergic hypersensitivity to angiotensin-converting enzyme inhibitor (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n10) 1269400003 | Concept name: Hypersensitivity to nalidixic acid (finding) | Score: -2.915 | Ancestor path: Hypersensitivity to nalidixic acid (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

------------------------------------------
Enhanced Dense Index: {'user_prompt': 'QUERY:\n"Known hypersensitivity to naproxen"\n\nCANDIDATES (choose from these only):\n1) 293625009 | Concept name: Allergy to naproxen (finding) | Score: 0.032 | Ancestor path: Allergy to naproxen (finding) → Allergy to non-steroidal anti-inflammatory agent (finding) → Allergy to drug (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n2) 372588000 | Concept name: Naproxen (substance) | Score: 0.030 | Ancestor path: Naproxen (substance) → Naphthalene (substance) → Polyaromatic hydrocarbon (substance) → Aromatic hydrocarbon (substance) → Hydrocarbon (substance) → Organic compound (substance) → Chemical categorized by structure (substance) → Chemical (substance) → Substance categorized by structure (substance)\n3) 1269400003 | Concept name: Hypersensitivity to nalidixic acid (finding) | Score: 0.029 | Ancestor path: Hypersensitivity to nalidixic acid (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n4) 42692007 | Concept name: Naproxen sodium (substance) | Score: 0.028 | Ancestor path: Naproxen sodium (substance) → Naphthalene (substance) → Polyaromatic hydrocarbon (substance) → Aromatic hydrocarbon (substance) → Hydrocarbon (substance) → Organic compound (substance) → Chemical categorized by structure (substance) → Chemical (substance) → Substance categorized by structure (substance)\n5) 295275004 | Concept name: Naproxen overdose (disorder) | Score: 0.026 | Ancestor path: Naproxen overdose (disorder) → Toxic effect of naphthalene (disorder) → Poisoning (disorder) → Intoxication (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n6) 218620007 | Concept name: Adverse reaction caused by naproxen (disorder) | Score: 0.025 | Ancestor path: Adverse reaction caused by naproxen (disorder) → Non-steroidal anti-inflammatory drug adverse reaction (disorder) → Non-opioid analgesic adverse reaction (disorder) → Analgesic adverse reaction (disorder) → Adverse reaction caused by drug (disorder) → Adverse reaction (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 11847009 | Concept name: Product containing naproxen (medicinal product) | Score: 0.025 | Ancestor path: Product containing naproxen (medicinal product) → Product containing naphthalene (product) → Medicinal product categorized by structure (product) → Medicinal product (product) → Pharmaceutical / biologic product (product) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 212603001 | Concept name: Naproxen poisoning (disorder) | Score: 0.024 | Ancestor path: Naproxen poisoning (disorder) → Toxic effect of naphthalene (disorder) → Poisoning (disorder) → Intoxication (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n9) 290282002 | Concept name: Intentional naproxen poisoning (disorder) | Score: 0.022 | Ancestor path: Intentional naproxen poisoning (disorder) → Naproxen poisoning (disorder) → Toxic effect of naphthalene (disorder) → Poisoning (disorder) → Intoxication (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n10) 295277007 | Concept name: Intentional naproxen overdose (disorder) | Score: 0.021 | Ancestor path: Intentional naproxen overdose (disorder) → Naproxen overdose (disorder) → Toxic effect of naphthalene (disorder) → Poisoning (disorder) → Intoxication (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n', 'parsed_output': {'direct_match': True, 'selected_id': '293625009', 'selected_term': 'Allergy to naproxen (finding)'}}

In [46]:
AUDIT_1 = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
AUDIT_2 = "results/20260415_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "a5aaf1db-1938-4073-9da4-c47f959d013e"
item_index = 8
call_name = "direct_match"
print(f"Are system prompts identical? {get_values(AUDIT_1, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt') == get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt')}")
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Simple Dense Index:", vals)
print("\n------------------------------------------")
vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Enhanced Dense Index:", vals)
# print("\n------------------------------------------")
# call_name = "route_or_fill"
# vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
#                   keys=["user_prompt","parsed_output"])
# print("values:", vals)

Are system prompts identical? True
Simple Dense Index: {'user_prompt': 'QUERY:\n"intestinal atony"\n\nCANDIDATES (choose from these only):\n1) 29479008 | Concept name: Atony of colon (disorder) | Score: 2.474 | Ancestor path: Atony of colon (disorder) → Disorder of colon (disorder) → Disorder of large intestine (disorder) → Disorder of lower gastrointestinal tract (disorder) → Disorder of abdominopelvic segment of trunk (disorder) → Disorder of trunk (disorder) → Finding of trunk structure (finding)\n2) 432414001 | Concept name: Constipation due to atony of colon (disorder) | Score: 1.013 | Ancestor path: Constipation due to atony of colon (disorder) → Functional disorder of intestine (disorder) → Disorder of intestine (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n3) 427225008 | Concept name: Atony of esophagus (disorder) | Score: 0.624 | Ancestor path: Atony of esophagus (disorder) → Disorder of esophagus (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Disorder of body system (disorder) → Disease (disorder)\n4) 9293002 | Concept name: Atony of uterus (disorder) | Score: -2.204 | Ancestor path: Atony of uterus (disorder) → Uterine inertia (disorder) → Abnormality of forces of labor (disorder) → Pelvic dystocia AND/OR uterine disorder (disorder) → Complication occurring during labor and delivery (disorder) → Maternal disorder during labor (disorder) → Complication occurring during pregnancy (disorder) → Maternal disorder during antenatal and/or intrapartum time period (disorder) → Finding related to pregnancy (finding)\n5) 287326003 | Concept name: Atony of gallbladder (disorder) | Score: -2.335 | Ancestor path: Atony of gallbladder (disorder) → Disorder of gallbladder (disorder) → Disorder of biliary tract (disorder) → Disorder of liver and/or biliary tract (disorder) → Disorder of abdomen (disorder) → Disorder of abdominopelvic segment of trunk (disorder) → Disorder of trunk (disorder) → Disease (disorder)\n6) 1255345008 | Concept name: Intestinal (intended site) | Score: -3.906 | Ancestor path: Intestinal (intended site) → Dose form intended site (intended site) → Qualifier value (qualifier value) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 76629003 | Concept name: Intestinal motility, function (observable entity) | Score: -4.442 | Ancestor path: Intestinal motility, function (observable entity) → Motor function (observable entity) → Nervous system function (observable entity) → Function (observable entity) → Observable entity (observable entity) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 392610001 | Concept name: Intestinal gas (substance) | Score: -5.273 | Ancestor path: Intestinal gas (substance) → Gaseous substance (substance) → Substance categorized by physical state (substance) → Substance (substance) → SNOMED CT Concept (SNOMED RT+CTV3)\n9) 59968008 | Concept name: Intestinal trichobezoar (disorder) | Score: -5.694 | Ancestor path: Intestinal trichobezoar (disorder) → Trichobezoar (disorder) → Bezoar (disorder) → Foreign body in digestive tract (disorder) → Foreign body (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n10) 187174008 | Concept name: Intestinal strongyloidiasis (disorder) | Score: -5.710 | Ancestor path: Intestinal strongyloidiasis (disorder) → Intestinal nematode infection (disorder) → Intestinal infection caused by Cestoda and/or Trematoda and/or Phylum Nematoda (disorder) → Intestinal parasitism (disorder) → Intestinal infectious disease (disorder) → Disorder of intestine (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

------------------------------------------
Enhanced Dense Index: {'user_prompt': 'QUERY:\n"intestinal atony"\n\nCANDIDATES (choose from these only):\n1) 427225008 | Concept name: Atony of esophagus (disorder) | Score: 0.033 | Ancestor path: Atony of esophagus (disorder) → Disorder of esophagus (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Disorder of body system (disorder) → Disease (disorder)\n2) 432414001 | Concept name: Constipation due to atony of colon (disorder) | Score: 0.031 | Ancestor path: Constipation due to atony of colon (disorder) → Functional disorder of intestine (disorder) → Disorder of intestine (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n3) 182513006 | Concept name: Intestinal intubation (procedure) | Score: 0.029 | Ancestor path: Intestinal intubation (procedure) → Intubation of gastrointestinal tract (procedure) → Intubation (procedure) → Insertion of tube (procedure) → Insertion procedure (procedure) → Introduction procedure (procedure) → Procedure by method (procedure)\n4) 29479008 | Concept name: Atony of colon (disorder) | Score: 0.026 | Ancestor path: Atony of colon (disorder) → Disorder of colon (disorder) → Disorder of large intestine (disorder) → Disorder of lower gastrointestinal tract (disorder) → Disorder of abdominopelvic segment of trunk (disorder) → Disorder of trunk (disorder) → Finding of trunk structure (finding)\n5) 9293002 | Concept name: Atony of uterus (disorder) | Score: 0.026 | Ancestor path: Atony of uterus (disorder) → Uterine inertia (disorder) → Abnormality of forces of labor (disorder) → Pelvic dystocia AND/OR uterine disorder (disorder) → Complication occurring during labor and delivery (disorder) → Maternal disorder during labor (disorder) → Complication occurring during pregnancy (disorder) → Maternal disorder during antenatal and/or intrapartum time period (disorder) → Finding related to pregnancy (finding)\n6) 81060008 | Concept name: Intestinal obstruction (disorder) | Score: 0.025 | Ancestor path: Intestinal obstruction (disorder) → Gastrointestinal obstruction (disorder) → Disorder of gastrointestinal tract (disorder) → Gastrointestinal tract finding (finding) → Digestive system finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 196753007 | Concept name: Gastric atonia (disorder) | Score: 0.016 | Ancestor path: Gastric atonia (disorder) → Disorder of function of stomach (disorder) → Disorder of stomach (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n8) 287326003 | Concept name: Atony of gallbladder (disorder) | Score: 0.016 | Ancestor path: Atony of gallbladder (disorder) → Disorder of gallbladder (disorder) → Disorder of biliary tract (disorder) → Disorder of liver and/or biliary tract (disorder) → Disorder of abdomen (disorder) → Disorder of abdominopelvic segment of trunk (disorder) → Disorder of trunk (disorder) → Disease (disorder)\n9) 266757004 | Concept name: Medical contraindication to procedure (situation) | Score: 0.015 | Ancestor path: Medical contraindication to procedure (situation) → Procedure contraindicated (situation) → Situation with explicit context (situation) → SNOMED CT Concept (SNOMED RT+CTV3)\n10) 410536001 | Concept name: Contraindicated (qualifier value) | Score: 0.015 | Ancestor path: Contraindicated (qualifier value) → Context values for actions (qualifier value) → Context values (qualifier value) → Qualifier value (qualifier value) → SNOMED CT Concept (SNOMED RT+CTV3)\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

In [47]:
AUDIT_1 = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
AUDIT_2 = "results/20260415_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "a5aaf1db-1938-4073-9da4-c47f959d013e"
item_index = 8
call_name = "route_or_fill"
print(f"Are system prompts identical? {get_values(AUDIT_1, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt') == get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt')}")
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Simple Dense Index:", vals)
print("\n------------------------------------------")
vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Enhanced Dense Index:", vals)
# print("\n------------------------------------------")
# call_name = "route_or_fill"
# vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
#                   keys=["user_prompt","parsed_output"])
# print("values:", vals)

Are system prompts identical? True
Simple Dense Index: {'user_prompt': 'QUERY:\nintestinal atony\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=intestinal atony\nsubstance_text=None\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 29479008 | Concept name: Atony of colon (disorder) | Score: 2.474 | Ancestor path: Atony of colon (disorder) → Disorder of colon (disorder) → Disorder of large intestine (disorder) → Disorder of lower gastrointestinal tract (disorder) → Disorder of abdominopelvic segment of trunk (disorder) → Disorder of trunk (disorder) → Finding of trunk structure (finding)\n2) 432414001 | Concept name: Constipation due to atony of colon (disorder) | Score: 1.013 | Ancestor path: Constipation due to atony of colon (disorder) → Functional disorder of intestine (disorder) → Disorder of intestine (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n3) 427225008 | Concept name: Atony of esophagus (disorder) | Score: 0.624 | Ancestor path: Atony of esophagus (disorder) → Disorder of esophagus (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Disorder of body system (disorder) → Disease (disorder)\n4) 9293002 | Concept name: Atony of uterus (disorder) | Score: -2.204 | Ancestor path: Atony of uterus (disorder) → Uterine inertia (disorder) → Abnormality of forces of labor (disorder) → Pelvic dystocia AND/OR uterine disorder (disorder) → Complication occurring during labor and delivery (disorder) → Maternal disorder during labor (disorder) → Complication occurring during pregnancy (disorder) → Maternal disorder during antenatal and/or intrapartum time period (disorder) → Finding related to pregnancy (finding)\n5) 287326003 | Concept name: Atony of gallbladder (disorder) | Score: -2.335 | Ancestor path: Atony of gallbladder (disorder) → Disorder of gallbladder (disorder) → Disorder of biliary tract (disorder) → Disorder of liver and/or biliary tract (disorder) → Disorder of abdomen (disorder) → Disorder of abdominopelvic segment of trunk (disorder) → Disorder of trunk (disorder) → Disease (disorder)\n6) 1255345008 | Concept name: Intestinal (intended site) | Score: -3.906 | Ancestor path: Intestinal (intended site) → Dose form intended site (intended site) → Qualifier value (qualifier value) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 76629003 | Concept name: Intestinal motility, function (observable entity) | Score: -4.442 | Ancestor path: Intestinal motility, function (observable entity) → Motor function (observable entity) → Nervous system function (observable entity) → Function (observable entity) → Observable entity (observable entity) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 392610001 | Concept name: Intestinal gas (substance) | Score: -5.273 | Ancestor path: Intestinal gas (substance) → Gaseous substance (substance) → Substance categorized by physical state (substance) → Substance (substance) → SNOMED CT Concept (SNOMED RT+CTV3)\n9) 59968008 | Concept name: Intestinal trichobezoar (disorder) | Score: -5.694 | Ancestor path: Intestinal trichobezoar (disorder) → Trichobezoar (disorder) → Bezoar (disorder) → Foreign body in digestive tract (disorder) → Foreign body (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n10) 187174008 | Concept name: Intestinal strongyloidiasis (disorder) | Score: -5.710 | Ancestor path: Intestinal strongyloidiasis (disorder) → Intestinal nematode infection (disorder) → Intestinal infection caused by Cestoda and/or Trematoda and/or Phylum Nematoda (disorder) → Intestinal parasitism (disorder) → Intestinal infectious disease (disorder) → Disorder of intestine (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n\nCAUSATIVE_AGENT_CANDIDATES:\nNONE\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'YES', 'selected_problem_id': '29479008', 'fills': {'causative_agent': 'N/A', 'severity': 'N/A', 'clinical_course': 'N/A'}}}

------------------------------------------
Enhanced Dense Index: {'user_prompt': 'QUERY:\nintestinal atony\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=intestinal atony\nsubstance_text=None\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 427225008 | Concept name: Atony of esophagus (disorder) | Score: 0.033 | Ancestor path: Atony of esophagus (disorder) → Disorder of esophagus (disorder) → Disorder of digestive organ (disorder) → Disorder of digestive system (disorder) → Disorder of body system (disorder) → Disease (disorder)\n2) 1255345008 | Concept name: Intestinal (intended site) | Score: 0.030 | Ancestor path: Intestinal (intended site) → Dose form intended site (intended site) → Qualifier value (qualifier value) → SNOMED CT Concept (SNOMED RT+CTV3)\n3) 432414001 | Concept name: Constipation due to atony of colon (disorder) | Score: 0.029 | Ancestor path: Constipation due to atony of colon (disorder) → Functional disorder of intestine (disorder) → Disorder of intestine (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n4) 81060008 | Concept name: Intestinal obstruction (disorder) | Score: 0.026 | Ancestor path: Intestinal obstruction (disorder) → Gastrointestinal obstruction (disorder) → Disorder of gastrointestinal tract (disorder) → Gastrointestinal tract finding (finding) → Digestive system finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n5) 113276009 | Concept name: Intestinal structure (body structure) | Score: 0.024 | Ancestor path: Intestinal structure (body structure) → Intra-abdominal digestive structure (body structure) → Digestive organ structure (body structure) → Body organ structure (body structure) → Anatomical structure (body structure) → Anatomical or acquired body structure (body structure) → Body structure (body structure) → SNOMED CT Concept (SNOMED RT+CTV3)\n6) 197476001 | Concept name: Intestinal malabsorption (disorder) | Score: 0.024 | Ancestor path: Intestinal malabsorption (disorder) → Malabsorption syndrome (disorder) → Disorder of gastrointestinal tract (disorder) → Disorder of digestive tract (disorder) → Disorder of digestive system (disorder) → Disorder of body system (disorder) → Disease (disorder)\n7) 392610001 | Concept name: Intestinal gas (substance) | Score: 0.022 | Ancestor path: Intestinal gas (substance) → Gaseous substance (substance) → Substance categorized by physical state (substance) → Substance (substance) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 102624003 | Concept name: Increased intestinal motility (finding) | Score: 0.020 | Ancestor path: Increased intestinal motility (finding) → Digestive system finding (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n9) 196753007 | Concept name: Gastric atonia (disorder) | Score: 0.016 | Ancestor path: Gastric atonia (disorder) → Disorder of function of stomach (disorder) → Disorder of stomach (disorder) → Disorder of abdomen (disorder) → Finding of abdomen (finding) → Finding of abdominopelvic segment of trunk (finding) → Finding of trunk structure (finding)\n10) 9293002 | Concept name: Atony of uterus (disorder) | Score: 0.016 | Ancestor path: Atony of uterus (disorder) → Uterine inertia (disorder) → Abnormality of forces of labor (disorder) → Pelvic dystocia AND/OR uterine disorder (disorder) → Complication occurring during labor and delivery (disorder) → Maternal disorder during labor (disorder) → Complication occurring during pregnancy (disorder) → Maternal disorder during antenatal and/or intrapartum time period (disorder) → Finding related to pregnancy (finding)\n\nCAUSATIVE_AGENT_CANDIDATES:\nNONE\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'YES', 'selected_problem_id': '432414001', 'fills': {'causative_agent': 'N/A', 'severity': 'N/A', 'clinical_course': 'N/A'}}}

In [48]:
AUDIT_1 = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
AUDIT_2 = "results/20260415_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "e3de56de-b707-405e-bf97-837070e5c744"
item_index = 5
call_name = "direct_match"
print(f"Are system prompts identical? {get_values(AUDIT_1, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt') == get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name, keys=['system_prompt']).get('system_prompt')}")
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Simple Dense Index:", vals)
print("\n------------------------------------------")
vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("Enhanced Dense Index:", vals)
# print("\n------------------------------------------")
# call_name = "route_or_fill"
# vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
#                   keys=["user_prompt","parsed_output"])
# print("values:", vals)

Are system prompts identical? True
Simple Dense Index: {'user_prompt': 'QUERY:\n"decompensated heart failure"\n\nCANDIDATES (choose from these only):\n1) 424404003 | Concept name: Decompensated chronic heart failure (disorder) | Score: 8.088 | Ancestor path: Decompensated chronic heart failure (disorder) → Chronic heart failure (disorder) → Chronic heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n2) 195111005 | Concept name: Decompensated cardiac failure (disorder) | Score: 7.989 | Ancestor path: Decompensated cardiac failure (disorder) → Heart failure (disorder) → Disorder of cardiac function (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n3) 314206003 | Concept name: Refractory heart failure (disorder) | Score: -0.196 | Ancestor path: Refractory heart failure (disorder) → Heart failure (disorder) → Disorder of cardiac function (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n4) 101281000119107 | Concept name: Congestive heart failure due to cardiomyopathy (disorder) | Score: -1.866 | Ancestor path: Congestive heart failure due to cardiomyopathy (disorder) → Cardiac complication (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n5) 10633002 | Concept name: Acute congestive heart failure (disorder) | Score: -2.103 | Ancestor path: Acute congestive heart failure (disorder) → Acute heart failure (disorder) → Acute heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n6) 46113002 | Concept name: Hypertensive heart failure (disorder) | Score: -2.203 | Ancestor path: Hypertensive heart failure (disorder) → Hypertensive heart disease (disorder) → Cardiac complication (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n7) 56675007 | Concept name: Acute heart failure (disorder) | Score: -2.289 | Ancestor path: Acute heart failure (disorder) → Acute heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n8) 42343007 | Concept name: Congestive heart failure (disorder) | Score: -2.332 | Ancestor path: Congestive heart failure (disorder) → Disorder of cardiac ventricle (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n9) 443254009 | Concept name: Acute systolic heart failure (disorder) | Score: -2.514 | Ancestor path: Acute systolic heart failure (disorder) → Acute heart failure (disorder) → Acute heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n10) 443343001 | Concept name: Acute diastolic heart failure (disorder) | Score: -2.594 | Ancestor path: Acute diastolic heart failure (disorder) → Acute heart failure (disorder) → Acute heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n', 'parsed_output': {'direct_match': True, 'selected_id': '195111005', 'selected_term': 'Decompensated cardiac failure (disorder)'}}

------------------------------------------
Enhanced Dense Index: {'user_prompt': 'QUERY:\n"decompensated heart failure"\n\nCANDIDATES (choose from these only):\n1) 424404003 | Concept name: Decompensated chronic heart failure (disorder) | Score: 0.033 | Ancestor path: Decompensated chronic heart failure (disorder) → Chronic heart failure (disorder) → Chronic heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n2) 42343007 | Concept name: Congestive heart failure (disorder) | Score: 0.031 | Ancestor path: Congestive heart failure (disorder) → Disorder of cardiac ventricle (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n3) 314206003 | Concept name: Refractory heart failure (disorder) | Score: 0.030 | Ancestor path: Refractory heart failure (disorder) → Heart failure (disorder) → Disorder of cardiac function (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n4) 84114007 | Concept name: Heart failure (disorder) | Score: 0.029 | Ancestor path: Heart failure (disorder) → Disorder of cardiac function (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n5) 46113002 | Concept name: Hypertensive heart failure (disorder) | Score: 0.029 | Ancestor path: Hypertensive heart failure (disorder) → Hypertensive heart disease (disorder) → Cardiac complication (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n6) 161505003 | Concept name: History of heart failure (situation) | Score: 0.028 | Ancestor path: History of heart failure (situation) → History of heart disorder (situation) → History of cardiovascular disease (situation) → History of disorder (situation) → History of clinical finding in subject (situation) → Finding with explicit context (situation) → Situation with explicit context (situation) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 395105005 | Concept name: Heart failure confirmed (situation) | Score: 0.028 | Ancestor path: Heart failure confirmed (situation) → Disorder confirmed (situation) → Clinical finding present (situation) → Finding with explicit context (situation) → Situation with explicit context (situation) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 418304008 | Concept name: Diastolic heart failure (disorder) | Score: 0.028 | Ancestor path: Diastolic heart failure (disorder) → Heart failure (disorder) → Disorder of cardiac function (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n9) 56675007 | Concept name: Acute heart failure (disorder) | Score: 0.028 | Ancestor path: Acute heart failure (disorder) → Acute heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n10) 48447003 | Concept name: Chronic heart failure (disorder) | Score: 0.028 | Ancestor path: Chronic heart failure (disorder) → Chronic heart disease (disorder) → Heart disease (disorder) → Disorder of mediastinum (disorder) → Disorder of thorax (disorder) → Finding of thoracic region (finding) → Finding of upper trunk (finding) → Finding of trunk structure (finding)\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

In [ ]:
AUDIT = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "6ae413ba-5a48-423f-8b8d-7a42661cf836"
item_index = 0
call_name = "direct_match"
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["system_prompt", "user_prompt","parsed_output"])
print("values:", vals)
# print("\n------------------------------------------")
# call_name = "route_or_fill"
# vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
#                   keys=["user_prompt","parsed_output"])
# print("values:", vals)

values: {'system_prompt': '\nYou are a strict biomedical terminology validator.\nYour role is to determine if a candidate is a LEXICAL and SEMANTIC identity match for the contraindication query.\n\nYour ONLY task:\n- Identify if a DIRECT MATCH exists among the provided candidates.\n- If a match exists, select exactly ONE candidate from the list.\n- Otherwise, return no match.\n\n--------------------\nDIRECT MATCH (STRICT)\n--------------------\nA candidate is a DIRECT MATCH only if it is an exact semantic equivalent. Do NOT bridge concepts even if they are clinically related.\n\n1) Lexical-Semantic Alignment:\n- The candidate must match the specificity and naming of the query.\n- Do NOT bridge concepts that use different primary terms even if they are clinically related.\n- If the query text and candidate label belong to different levels of the hierarchy, return no match.\n2) Temporal/Contextual Scope:\n- "Post-X" is NOT a match for "X".\n- "History of X" is NOT a match for "X".\n- If the query implies a state after an event and the candidate is only the event, return no match.\n3) Meaning Completeness:\n- Do NOT select a candidate that represents only part of the query.\n4) Semantic Type Guardrail:\n- If the query implies a condition/state, do NOT select a procedure concept unless the query explicitly describes a procedure.\n5) Hierarchical Granularity:\n- A match must exist at the same level of specificity as the query.\n- A broader parent or narrower child is NOT a direct match.\n\n--------------------\nCANDIDATE ELIGIBILITY FILTERS\n--------------------\nUnless the query explicitly describes a procedure or product, do NOT select candidates whose label indicates:\n- procedure\n- administration\n- vaccination\n- other overly broad parent concepts when the query is specific\n\n--------------------\nOUTPUT FORMAT\n--------------------\nReturn ONLY minified JSON followed immediately by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"direct_match":true/false,"selected_id":"<candidate id or N/A>","selected_term":"<candidate term or N/A>"}<<END_JSON>>\n\nRules:\n- If direct_match=true, selected_id MUST be from the candidate list.\n- If direct_match=false, selected_id and selected_term MUST be N/A.\n', 'user_prompt': 'QUERY:\n"Known hypersensitivity to naproxen"\n\nCANDIDATES (choose from these only):\n1) 609534005 | Concept name: Non-allergic hypersensitivity to losartan (finding) | Score: -1.199 | Ancestor path: Non-allergic hypersensitivity to losartan (finding) → Non-allergic hypersensitivity to angiotensin II receptor antagonist (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n2) 218620007 | Concept name: Adverse reaction caused by naproxen (disorder) | Score: -1.312 | Ancestor path: Adverse reaction caused by naproxen (disorder) → Non-steroidal anti-inflammatory drug adverse reaction (disorder) → Non-opioid analgesic adverse reaction (disorder) → Analgesic adverse reaction (disorder) → Adverse reaction caused by drug (disorder) → Adverse reaction (disorder) → Disease (disorder) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n3) 114931000119103 | Concept name: Hypersensitivity to abacavir (finding) | Score: -1.963 | Ancestor path: Hypersensitivity to abacavir (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n4) 1269353008 | Concept name: Hypersensitivity to gentamicin (finding) | Score: -1.974 | Ancestor path: Hypersensitivity to gentamicin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n5) 293625009 | Concept name: Allergy to naproxen (finding) | Score: -2.290 | Ancestor path: Allergy to naproxen (finding) → Allergy to non-steroidal anti-inflammatory agent (finding) → Allergy to drug (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n6) 609540003 | Concept name: Non-allergic hypersensitivity to enalapril (finding) | Score: -2.493 | Ancestor path: Non-allergic hypersensitivity to enalapril (finding) → Non-allergic hypersensitivity to angiotensin-converting enzyme inhibitor (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n7) 1269354002 | Concept name: Hypersensitivity to erythromycin (finding) | Score: -2.611 | Ancestor path: Hypersensitivity to erythromycin (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n8) 18361000122109 | Concept name: Non-allergic hypersensitivity to moexipril (finding) | Score: -2.613 | Ancestor path: Non-allergic hypersensitivity to moexipril (finding) → Non-allergic hypersensitivity to angiotensin-converting enzyme inhibitor (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n9) 609545008 | Concept name: Non-allergic hypersensitivity to ramipril (finding) | Score: -2.635 | Ancestor path: Non-allergic hypersensitivity to ramipril (finding) → Non-allergic hypersensitivity to angiotensin-converting enzyme inhibitor (finding) → Non-allergic hypersensitivity to drug or medicament (finding) → Propensity to adverse reactions to drug (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n10) 1269400003 | Concept name: Hypersensitivity to nalidixic acid (finding) | Score: -2.915 | Ancestor path: Hypersensitivity to nalidixic acid (finding) → Hypersensitivity disposition (finding) → Propensity to adverse reaction (finding) → Clinical finding (finding) → SNOMED CT Concept (SNOMED RT+CTV3)\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

In [100]:
AUDIT = "results/20260414_isolation/100_bm25_only/runtime_audit.jsonl"
SET_ID = "fe08bcd5-4d14-4c2d-940c-b7968f9a89f0"
item_index = 4
call_name = "route_or_fill"
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("values:", vals)
# print("\n------------------------------------------")
# call_name = "route_or_fill"
# vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
#                   keys=["user_prompt","parsed_output"])
# print("values:", vals)

values: {'user_prompt': 'QUERY:\nMycobacterial infection of the eye\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=infection\nsubstance_text=Mycobacterial\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 838338001 | Concept name: Bacterial infection due to human immunodeficiency virus infection (disorder) | Score: 2.612\n2) 63459005 | Concept name: Clinical infection (disorder) | Score: 1.891\n3) 275393007 | Concept name: Oral infection (disorder) | Score: 1.444\n4) 312155003 | Concept name: Genital infection (disorder) | Score: 0.974\n5) 10443009 | Concept name: Localized infection (disorder) | Score: 0.844\n6) 76844004 | Concept name: Local infection of wound (disorder) | Score: 0.423\n7) 260976002 | Concept name: Presence of infection (qualifier value) | Score: 0.027\n8) 186747009 | Concept name: Coronavirus infection (disorder) | Score: -0.089\n9) 41659003 | Concept name: Haemophilus infection (disorder) | Score: -0.131\n10) 111910009 | Concept name: Amebic infection (disorder) | Score: -0.430\n\nCAUSATIVE_AGENT_CANDIDATES:\n1) 716340006 | Concept name: Mycobacterium bacteremicum (organism) | Score: 6.224\n2) 785918006 | Concept name: Genus Mycobacteroides (organism) | Score: 5.408\n3) 243368001 | Concept name: Genus Mycobacterium (organism) | Score: 5.326\n4) 712909005 | Concept name: Mycobacterium vulneris (organism) | Score: 5.270\n5) 113861009 | Concept name: Mycobacterium tuberculosis (organism) | Score: 5.109\n6) 427768005 | Concept name: Mycobacterium kubicae (organism) | Score: 4.974\n7) 432888001 | Concept name: Mycobacterium phocaicum (organism) | Score: 4.917\n8) 1285313007 | Concept name: Order Mycobacteriales (organism) | Score: 4.792\n9) 70801007 | Concept name: Mycobacterium microti (organism) | Score: 4.649\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'N/A', 'selected_problem_id': '63459005', 'fills': {'causative_agent': '243368001', 'severity': 'N/A', 'clinical_course': 'N/A'}}}

In [62]:
# strict barely better than anc onnly
AUDIT = "results/20260414_isolation/001_strict_only/runtime_audit.jsonl"
AUDIT_2 = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "fe08bcd5-4d14-4c2d-940c-b7968f9a89f0"
item_index = 4
call_name = "direct_match"
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["system_prompt"])
print("values:", vals)
print("\n------------------------------------------")
# call_name = "route_or_fill"
vals = get_values(AUDIT_2, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["system_prompt"])
print("values:", vals)

values: {'system_prompt': '\nYou are a strict biomedical terminology validator.\nYour role is to determine if a candidate is a LEXICAL and SEMANTIC identity match for the contraindication query.\n\nYour ONLY task:\n- Identify if a DIRECT MATCH exists among the provided candidates.\n- If a match exists, select exactly ONE candidate from the list.\n- Otherwise, return no match.\n\nWhen in doubt, return no match. A false negative here is recoverable; a false positive is not.\n\n--------------------\nDIRECT MATCH (STRICT)\n--------------------\nA candidate is a DIRECT MATCH only if its label is an exact lexical-semantic equivalent to the query — identical clinical meaning, identical ontological level, identical primary term.\n\n1) Primary Term Identity:\n- The root condition word used in the query MUST be the same root condition word in the candidate label.\n- Clinically related terms that are NOT interchangeable in SNOMED CT:\n    * "Hypersensitivity" ≠ "Allergy"  (Allergy is a subtype of Hypersensitivity — different concepts)\n    * "Hypersensitivity" ≠ "Sensitivity"\n    * "Disorder" ≠ "Finding"\n    * "Reaction" ≠ "Hypersensitivity"\n- If the query says "hypersensitivity to X" and the candidate says "allergy to X", return no match even if they seem clinically equivalent. They occupy different positions in the SNOMED CT hierarchy.\n\n2) Hierarchical Granularity — subtypes and supertypes are both wrong:\n- A narrower (more specific) concept is NOT a match: "Allergy to ibuprofen" is NOT a match for "Hypersensitivity to ibuprofen".\n- A broader (more general) concept is NOT a match: "Hypersensitivity disorder" is NOT a match for "Hypersensitivity to ibuprofen".\n- The candidate must encode exactly the same meaning — not more specific, not more general.\n\n3) Meaning Completeness:\n- Do NOT select a candidate that represents only part of the query meaning.\n- Do NOT select a candidate that adds qualifiers not present in the query (e.g., "known", "documented", "acute").\n\n4) Temporal/Contextual Scope:\n- "Post-X" is NOT a match for "X".\n- "History of X" is NOT a match for "X".\n- If the query implies a state after an event and the candidate is only the event, return no match.\n\n5) Semantic Type Guardrail:\n- If the query implies a condition/state, do NOT select a procedure concept unless the query explicitly describes a procedure.\n\n--------------------\nCANDIDATE ELIGIBILITY FILTERS\n--------------------\nUnless the query explicitly describes a procedure or product, do NOT select candidates whose label indicates:\n- procedure\n- administration\n- vaccination\n- other overly broad parent concepts when the query is specific\n\n--------------------\nOUTPUT FORMAT\n--------------------\nReturn ONLY minified JSON followed immediately by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"direct_match":true/false,"selected_id":"<candidate id or N/A>","selected_term":"<candidate term or N/A>"}<<END_JSON>>\n\nRules:\n- If direct_match=true, selected_id MUST be from the candidate list.\n- If direct_match=false, selected_id and selected_term MUST be N/A.\n'}

------------------------------------------
values: {'system_prompt': '\nYou are a strict biomedical terminology validator.\nYour role is to determine if a candidate is a LEXICAL and SEMANTIC identity match for the contraindication query.\n\nYour ONLY task:\n- Identify if a DIRECT MATCH exists among the provided candidates.\n- If a match exists, select exactly ONE candidate from the list.\n- Otherwise, return no match.\n\n--------------------\nDIRECT MATCH (STRICT)\n--------------------\nA candidate is a DIRECT MATCH only if it is an exact semantic equivalent. Do NOT bridge concepts even if they are clinically related.\n\n1) Lexical-Semantic Alignment:\n- The candidate must match the specificity and naming of the query.\n- Do NOT bridge concepts that use different primary terms even if they are clinically related.\n- If the query text and candidate label belong to different levels of the hierarchy, return no match.\n2) Temporal/Contextual Scope:\n- "Post-X" is NOT a match for "X".\n- "History of X" is NOT a match for "X".\n- If the query implies a state after an event and the candidate is only the event, return no match.\n3) Meaning Completeness:\n- Do NOT select a candidate that represents only part of the query.\n4) Semantic Type Guardrail:\n- If the query implies a condition/state, do NOT select a procedure concept unless the query explicitly describes a procedure.\n5) Hierarchical Granularity:\n- A match must exist at the same level of specificity as the query.\n- A broader parent or narrower child is NOT a direct match.\n\n--------------------\nCANDIDATE ELIGIBILITY FILTERS\n--------------------\nUnless the query explicitly describes a procedure or product, do NOT select candidates whose label indicates:\n- procedure\n- administration\n- vaccination\n- other overly broad parent concepts when the query is specific\n\n--------------------\nOUTPUT FORMAT\n--------------------\nReturn ONLY minified JSON followed immediately by <<END_JSON>>.\nDo NOT use markdown fences.\nDo NOT include explanations or extra fields.\n\nSchema:\n{"direct_match":true/false,"selected_id":"<candidate id or N/A>","selected_term":"<candidate term or N/A>"}<<END_JSON>>\n\nRules:\n- If direct_match=true, selected_id MUST be from the candidate list.\n- If direct_match=false, selected_id and selected_term MUST be N/A.\n'}

#### Hypersensitivity not getting pulled

In [36]:
# No hypersensitivity 
AUDIT = "results/20260414_isolation/100_bm25_only/runtime_audit.jsonl"
# AUDIT_2 = "results/20260414_isolation/010_anc_only/runtime_audit.jsonl"
SET_ID = "b0c91667-ab6f-481d-a592-62da8a52abf7"
item_index = 1
call_name = "direct_match"
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("values:", vals)
print("\n------------------------------------------")
call_name = "route_or_fill"
vals = get_values(AUDIT, SET_ID, item_index=item_index, call_name=call_name,
                  keys=["user_prompt","parsed_output"])
print("values:", vals)

values: {'user_prompt': 'QUERY:\n"Known hypersensitivity to atropine"\n\nCANDIDATES (choose from these only):\n1) 1269398002 | Concept name: Hypersensitivity to minocycline (finding) | Score: -0.409\n2) 1269354002 | Concept name: Hypersensitivity to erythromycin (finding) | Score: -1.791\n3) 1269353008 | Concept name: Hypersensitivity to gentamicin (finding) | Score: -2.071\n4) 1269352003 | Concept name: Hypersensitivity to succinylcholine (finding) | Score: -2.394\n5) 114931000119103 | Concept name: Hypersensitivity to abacavir (finding) | Score: -2.559\n6) 1269395004 | Concept name: Hypersensitivity to hydrocortisone (finding) | Score: -2.713\n7) 292534001 | Concept name: Atropine adverse reaction (disorder) | Score: -2.784\n8) 1269400003 | Concept name: Hypersensitivity to nalidixic acid (finding) | Score: -2.878\n9) 609548005 | Concept name: Non-allergic hypersensitivity to aspartame (finding) | Score: -2.981\n10) 1163445008 | Concept name: Hypersensitivity to polysorbate-80 (finding) | Score: -3.225\n', 'parsed_output': {'direct_match': False, 'selected_id': 'N/A', 'selected_term': 'N/A'}}

------------------------------------------
values: {'user_prompt': 'QUERY:\nKnown hypersensitivity to atropine\n\nEXTRACTED_FIELDS:\ncontraindication_state_text=hypersensitivity disposition\nsubstance_text=atropine\nseverity_span=None\ncourse_span=None\n\nATTRIBUTE_TABLE:\n{"causative_agent":246075003,"severity":246112005,"clinical_course":263502005}\n\nFOCUS_CANDIDATES:\n1) 609433001 | Concept name: Hypersensitivity disposition (finding) | Score: 7.588\n2) 609396006 | Concept name: Non-allergic hypersensitivity disposition (finding) | Score: 6.592\n3) 421961002 | Concept name: Hypersensitivity reaction (disorder) | Score: -0.200\n4) 234993000 | Concept name: Hypersensitivity gingivitis (disorder) | Score: -0.551\n5) 473010000 | Concept name: Hypersensitivity condition (finding) | Score: -0.657\n6) 735449006 | Concept name: Hypersensitivity reaction caused by food (disorder) | Score: -0.842\n7) 421369008 | Concept name: Emotional hypersensitivity (finding) | Score: -1.501\n8) 426760008 | Concept name: Delayed hypersensitivity disorder (disorder) | Score: -1.653\n9) 21626009 | Concept name: Cutaneous hypersensitivity (disorder) | Score: -1.849\n10) 472963003 | Concept name: Hypersensitivity process (qualifier value) | Score: -1.875\n\nCAUSATIVE_AGENT_CANDIDATES:\n1) 372832002 | Concept name: Atropine (substance) | Score: 6.938\n2) 391795000 | Concept name: Atropine methonitrate (substance) | Score: 5.958\n3) 73949004 | Concept name: Product containing atropine (medicinal product) | Score: 5.748\n4) 74237004 | Concept name: Atropine sulfate (substance) | Score: 5.674\n5) 1268950007 | Concept name: Atropine sulfate anhydrous (substance) | Score: 5.565\n6) 725735006 | Concept name: Atropine sulfate monohydrate (substance) | Score: 5.528\n7) 349946007 | Concept name: Product containing atropine in parenteral dose form (medicinal product form) | Score: 4.589\n8) 347097005 | Concept name: Product containing precisely atropine sulfate 5 milligram/1 milliliter conventional release eye drops (clinical drug) | Score: 4.087\n\nSEVERITY_CANDIDATES:\nNONE\n\nCLINICAL_COURSE_CANDIDATES:\nNONE\n', 'parsed_output': {'post_decision': 'YES', 'selected_problem_id': '609433001', 'fills': {'causative_agent': '372832002', 'severity': 'N/A', 'clinical_course': 'N/A'}}}

In [3]:
# onetime fix for agg_csv 
import subprocess
def run_rewrite(input_file, output_file):
    cmd = [
        "python3",
        "rewrite_agg_csv.py",
        "--in", input_file,
        "--out", output_file
    ]
    subprocess.run(cmd, check=True)

In [11]:
# get list of all jsonl files from a given directory. Have subdirectories too, so need to walk through them
# Need to specify a directory to look into
import os
target = "results/20260414_isolation"
for root, dirs, files in os.walk(target):
    for filename in files:
        if filename == "aggregated_results.jsonl":
            input = os.path.join(root, filename)
            output = os.path.join(root, "aggregated_results_rewrite.csv")
            run_rewrite(input, output)
            print(f"Found file: {input}")
            print(f"Rewriting to: {output}")

Read 98 SPL groups (385 items) from: results/20260414_isolation/101_bm25_strict/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/101_bm25_strict/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/101_bm25_strict/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/101_bm25_strict/aggregated_results_rewrite.csv
Read 98 SPL groups (385 items) from: results/20260414_isolation/110_bm25_anc/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/110_bm25_anc/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/110_bm25_anc/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/110_bm25_anc/aggregated_results_rewrite.csv
Read 98 SPL groups (385 items) from: results/20260414_isolation/111_all_on/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/111_all_on/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/111_all_on/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/111_all_on/aggregated_results_rewrite.csv
Read 97 SPL groups (383 items) from: results/20260414_isolation/011_anc_strict/aggregated_results.jsonl
Wrote CSV (383 rows) to: results/20260414_isolation/011_anc_strict/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/011_anc_strict/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/011_anc_strict/aggregated_results_rewrite.csv
Read 98 SPL groups (385 items) from: results/20260414_isolation/000_baseline/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/000_baseline/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/000_baseline/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/000_baseline/aggregated_results_rewrite.csv
Read 98 SPL groups (385 items) from: results/20260414_isolation/001_strict_only/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/001_strict_only/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/001_strict_only/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/001_strict_only/aggregated_results_rewrite.csv
Read 98 SPL groups (385 items) from: results/20260414_isolation/010_anc_only/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/010_anc_only/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/010_anc_only/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/010_anc_only/aggregated_results_rewrite.csv
Read 98 SPL groups (385 items) from: results/20260414_isolation/100_bm25_only/aggregated_results.jsonl
Wrote CSV (385 rows) to: results/20260414_isolation/100_bm25_only/aggregated_results_rewrite.csv
Found file: results/20260414_isolation/100_bm25_only/aggregated_results.jsonl
Rewriting to: results/20260414_isolation/100_bm25_only/aggregated_results_rewrite.csv

In [50]:
from agent_runner import evaluate_aggregated_predictions
import json
import os
# gold_csv = "results/contra_gold_100_2.csv"
gold_csv = "results/contra_gold_100_3.csv"
# aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
# eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
# eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"
targets = ["results/20260414_isolation", "results/20260415_isolation"]
bools = [True, False]
for target in targets:
    for decoupled in bools:
        for root, dirs, files in os.walk(target):
            for filename in files:
                if filename == "aggregated_results_rewrite.csv":
                    aggregated_csv = os.path.join(root, filename)
                    json_name = "evaluation_metrics_decoupled.json" if decoupled else "evaluation_metrics_coupled.json"
                    csv_name = "evaluation_details_decoupled.csv" if decoupled else "evaluation_details_coupled.csv"
                    eval_json = os.path.join(root, json_name)
                    eval_details_csv = os.path.join(root, csv_name)
                    metrics = evaluate_aggregated_predictions(
                                pred_csv=aggregated_csv,
                                gold_csv=gold_csv,
                                out_json=eval_json,
                                out_details_csv=eval_details_csv,
                                decoupled=decoupled,
                                min_pair_score=0.8
                            )
                    print(json.dumps(metrics, indent=2))
                    print(f"Wrote evaluation metrics to: {eval_json}")
                    print(f"Wrote evaluation details to: {eval_details_csv}")

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7587.56it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/101_bm25_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 131,
    "fp": 101,
    "fn": 101,
    "precision": 0.5646551724137931,
    "recall": 0.5646551724137931,
    "f1": 0.5646551724137931
  },
  "concept_level": {
    "tp": 275.65,
    "fp": 69.44999999999999,
    "fn": 102.45000000000002,
    "precision": 0.7987539843523617,
    "recall": 0.7290399365247288,
    "f1": 0.7623064159292033
  }
}
Wrote details: results/20260414_isolation/101_bm25_strict/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/101_bm25_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 131,
    "fp": 101,
    "fn": 101,
    "precision": 0.5646551724137931,
    "recall": 0.5646551724137931,
    "f1": 0.5646551724137931
  },
  "concept_level": {
    "tp": 275.65,
    "fp": 69.44999999999999,
    "fn": 102.45000000000002,
    "precision": 0.7987539843523617,
    "recall": 0.7290399365247288,
    "f1": 0.7623064159292033
  }
}
Wrote evaluation metrics to: results/20260414_isolation/101_bm25_strict/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/101_bm25_strict/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 4900.31it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/110_bm25_anc/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 102,
    "fn": 102,
    "precision": 0.5603448275862069,
    "recall": 0.5603448275862069,
    "f1": 0.5603448275862069
  },
  "concept_level": {
    "tp": 267.09999999999997,
    "fp": 74.1,
    "fn": 111.10000000000001,
    "precision": 0.7828253223915592,
    "recall": 0.7062400846113167,
    "f1": 0.7425632471504031
  }
}
Wrote details: results/20260414_isolation/110_bm25_anc/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/110_bm25_anc/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 102,
    "fn": 102,
    "precision": 0.5603448275862069,
    "recall": 0.5603448275862069,
    "f1": 0.5603448275862069
  },
  "concept_level": {
    "tp": 267.09999999999997,
    "fp": 74.1,
    "fn": 111.10000000000001,
    "precision": 0.7828253223915592,
    "recall": 0.7062400846113167,
    "f1": 0.7425632471504031
  }
}
Wrote evaluation metrics to: results/20260414_isolation/110_bm25_anc/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/110_bm25_anc/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 8039.58it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/111_all_on/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 132,
    "fp": 100,
    "fn": 100,
    "precision": 0.5689655172413793,
    "recall": 0.5689655172413793,
    "f1": 0.5689655172413793
  },
  "concept_level": {
    "tp": 280.25,
    "fp": 71.94999999999999,
    "fn": 97.95000000000002,
    "precision": 0.7957126632595116,
    "recall": 0.7410100475938656,
    "f1": 0.7673877327491785
  }
}
Wrote details: results/20260414_isolation/111_all_on/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/111_all_on/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 132,
    "fp": 100,
    "fn": 100,
    "precision": 0.5689655172413793,
    "recall": 0.5689655172413793,
    "f1": 0.5689655172413793
  },
  "concept_level": {
    "tp": 280.25,
    "fp": 71.94999999999999,
    "fn": 97.95000000000002,
    "precision": 0.7957126632595116,
    "recall": 0.7410100475938656,
    "f1": 0.7673877327491785
  }
}
Wrote evaluation metrics to: results/20260414_isolation/111_all_on/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/111_all_on/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7492.34it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/011_anc_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 383,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 230,
    "fp": 117,
    "fn": 84,
    "precision": 0.6628242074927954,
    "recall": 0.732484076433121,
    "f1": 0.6959152798789713
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 97,
    "fn": 97,
    "precision": 0.5782608695652174,
    "recall": 0.5782608695652174,
    "f1": 0.5782608695652174
  },
  "concept_level": {
    "tp": 285.65,
    "fp": 58.54999999999998,
    "fn": 88.55000000000001,
    "precision": 0.829895409645555,
    "recall": 0.7633618385889898,
    "f1": 0.795239420935412
  }
}
Wrote details: results/20260414_isolation/011_anc_strict/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/011_anc_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 383,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 230,
    "fp": 117,
    "fn": 84,
    "precision": 0.6628242074927954,
    "recall": 0.732484076433121,
    "f1": 0.6959152798789713
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 97,
    "fn": 97,
    "precision": 0.5782608695652174,
    "recall": 0.5782608695652174,
    "f1": 0.5782608695652174
  },
  "concept_level": {
    "tp": 285.65,
    "fp": 58.54999999999998,
    "fn": 88.55000000000001,
    "precision": 0.829895409645555,
    "recall": 0.7633618385889898,
    "f1": 0.795239420935412
  }
}
Wrote evaluation metrics to: results/20260414_isolation/011_anc_strict/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/011_anc_strict/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 5942.79it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/000_baseline/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 128,
    "fp": 104,
    "fn": 104,
    "precision": 0.5517241379310345,
    "recall": 0.5517241379310345,
    "f1": 0.5517241379310345
  },
  "concept_level": {
    "tp": 263.85,
    "fp": 69.25,
    "fn": 114.25000000000003,
    "precision": 0.7921044731311918,
    "recall": 0.6978312615710129,
    "f1": 0.7419853768278964
  }
}
Wrote details: results/20260414_isolation/000_baseline/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/000_baseline/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 128,
    "fp": 104,
    "fn": 104,
    "precision": 0.5517241379310345,
    "recall": 0.5517241379310345,
    "f1": 0.5517241379310345
  },
  "concept_level": {
    "tp": 263.85,
    "fp": 69.25,
    "fn": 114.25000000000003,
    "precision": 0.7921044731311918,
    "recall": 0.6978312615710129,
    "f1": 0.7419853768278964
  }
}
Wrote evaluation metrics to: results/20260414_isolation/000_baseline/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/000_baseline/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7909.12it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/001_strict_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 99,
    "fn": 99,
    "precision": 0.5732758620689655,
    "recall": 0.5732758620689655,
    "f1": 0.5732758620689655
  },
  "concept_level": {
    "tp": 284.8,
    "fp": 63.29999999999999,
    "fn": 93.30000000000001,
    "precision": 0.8181557023843723,
    "recall": 0.7532398836286697,
    "f1": 0.7843569264665381
  }
}
Wrote details: results/20260414_isolation/001_strict_only/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/001_strict_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 99,
    "fn": 99,
    "precision": 0.5732758620689655,
    "recall": 0.5732758620689655,
    "f1": 0.5732758620689655
  },
  "concept_level": {
    "tp": 284.8,
    "fp": 63.29999999999999,
    "fn": 93.30000000000001,
    "precision": 0.8181557023843723,
    "recall": 0.7532398836286697,
    "f1": 0.7843569264665381
  }
}
Wrote evaluation metrics to: results/20260414_isolation/001_strict_only/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/001_strict_only/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7821.10it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/010_anc_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 129,
    "fp": 103,
    "fn": 103,
    "precision": 0.5560344827586207,
    "recall": 0.5560344827586207,
    "f1": 0.5560344827586207
  },
  "concept_level": {
    "tp": 271.5,
    "fp": 65.69999999999999,
    "fn": 106.7,
    "precision": 0.8051601423487544,
    "recall": 0.7178741406663142,
    "f1": 0.7590159351411797
  }
}
Wrote details: results/20260414_isolation/010_anc_only/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/010_anc_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 129,
    "fp": 103,
    "fn": 103,
    "precision": 0.5560344827586207,
    "recall": 0.5560344827586207,
    "f1": 0.5560344827586207
  },
  "concept_level": {
    "tp": 271.5,
    "fp": 65.69999999999999,
    "fn": 106.7,
    "precision": 0.8051601423487544,
    "recall": 0.7178741406663142,
    "f1": 0.7590159351411797
  }
}
Wrote evaluation metrics to: results/20260414_isolation/010_anc_only/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/010_anc_only/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7719.65it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/100_bm25_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 102,
    "fn": 102,
    "precision": 0.5603448275862069,
    "recall": 0.5603448275862069,
    "f1": 0.5603448275862069
  },
  "concept_level": {
    "tp": 261.19999999999993,
    "fp": 70.89999999999999,
    "fn": 116.90000000000002,
    "precision": 0.7865100873230955,
    "recall": 0.6908225337212377,
    "f1": 0.7355674457899184
  }
}
Wrote details: results/20260414_isolation/100_bm25_only/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/100_bm25_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 102,
    "fn": 102,
    "precision": 0.5603448275862069,
    "recall": 0.5603448275862069,
    "f1": 0.5603448275862069
  },
  "concept_level": {
    "tp": 261.19999999999993,
    "fp": 70.89999999999999,
    "fn": 116.90000000000002,
    "precision": 0.7865100873230955,
    "recall": 0.6908225337212377,
    "f1": 0.7355674457899184
  }
}
Wrote evaluation metrics to: results/20260414_isolation/100_bm25_only/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260414_isolation/100_bm25_only/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7270.76it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/101_bm25_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 131,
    "fp": 218,
    "fn": 183,
    "precision": 0.3753581661891118,
    "recall": 0.4171974522292994,
    "f1": 0.39517345399698345
  },
  "concept_level": {
    "tp": 275.65,
    "fp": 244.45000000000005,
    "fn": 243.45000000000005,
    "precision": 0.5299942318784848,
    "recall": 0.5310152186476593,
    "f1": 0.5305042340261739
  }
}
Wrote details: results/20260414_isolation/101_bm25_strict/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/101_bm25_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 131,
    "fp": 218,
    "fn": 183,
    "precision": 0.3753581661891118,
    "recall": 0.4171974522292994,
    "f1": 0.39517345399698345
  },
  "concept_level": {
    "tp": 275.65,
    "fp": 244.45000000000005,
    "fn": 243.45000000000005,
    "precision": 0.5299942318784848,
    "recall": 0.5310152186476593,
    "f1": 0.5305042340261739
  }
}
Wrote evaluation metrics to: results/20260414_isolation/101_bm25_strict/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/101_bm25_strict/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 2548.65it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/110_bm25_anc/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 219,
    "fn": 184,
    "precision": 0.37249283667621774,
    "recall": 0.4140127388535032,
    "f1": 0.39215686274509803
  },
  "concept_level": {
    "tp": 267.09999999999997,
    "fp": 247.10000000000005,
    "fn": 252.10000000000005,
    "precision": 0.5194476857253986,
    "recall": 0.5144453004622495,
    "f1": 0.5169343913295915
  }
}
Wrote details: results/20260414_isolation/110_bm25_anc/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/110_bm25_anc/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 219,
    "fn": 184,
    "precision": 0.37249283667621774,
    "recall": 0.4140127388535032,
    "f1": 0.39215686274509803
  },
  "concept_level": {
    "tp": 267.09999999999997,
    "fp": 247.10000000000005,
    "fn": 252.10000000000005,
    "precision": 0.5194476857253986,
    "recall": 0.5144453004622495,
    "f1": 0.5169343913295915
  }
}
Wrote evaluation metrics to: results/20260414_isolation/110_bm25_anc/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/110_bm25_anc/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 5839.65it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/111_all_on/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 132,
    "fp": 217,
    "fn": 182,
    "precision": 0.37822349570200575,
    "recall": 0.42038216560509556,
    "f1": 0.3981900452488688
  },
  "concept_level": {
    "tp": 280.25,
    "fp": 247.95000000000005,
    "fn": 238.95000000000005,
    "precision": 0.5305755395683452,
    "recall": 0.5397727272727272,
    "f1": 0.5351346190567118
  }
}
Wrote details: results/20260414_isolation/111_all_on/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/111_all_on/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 132,
    "fp": 217,
    "fn": 182,
    "precision": 0.37822349570200575,
    "recall": 0.42038216560509556,
    "f1": 0.3981900452488688
  },
  "concept_level": {
    "tp": 280.25,
    "fp": 247.95000000000005,
    "fn": 238.95000000000005,
    "precision": 0.5305755395683452,
    "recall": 0.5397727272727272,
    "f1": 0.5351346190567118
  }
}
Wrote evaluation metrics to: results/20260414_isolation/111_all_on/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/111_all_on/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 8303.41it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/011_anc_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 383,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 230,
    "fp": 117,
    "fn": 84,
    "precision": 0.6628242074927954,
    "recall": 0.732484076433121,
    "f1": 0.6959152798789713
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 214,
    "fn": 181,
    "precision": 0.38328530259365995,
    "recall": 0.42356687898089174,
    "f1": 0.4024205748865355
  },
  "concept_level": {
    "tp": 285.65,
    "fp": 236.55000000000004,
    "fn": 233.55000000000004,
    "precision": 0.5470126388356951,
    "recall": 0.5501733436055469,
    "f1": 0.5485884386402918
  }
}
Wrote details: results/20260414_isolation/011_anc_strict/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/011_anc_strict/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 383,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 230,
    "fp": 117,
    "fn": 84,
    "precision": 0.6628242074927954,
    "recall": 0.732484076433121,
    "f1": 0.6959152798789713
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 214,
    "fn": 181,
    "precision": 0.38328530259365995,
    "recall": 0.42356687898089174,
    "f1": 0.4024205748865355
  },
  "concept_level": {
    "tp": 285.65,
    "fp": 236.55000000000004,
    "fn": 233.55000000000004,
    "precision": 0.5470126388356951,
    "recall": 0.5501733436055469,
    "f1": 0.5485884386402918
  }
}
Wrote evaluation metrics to: results/20260414_isolation/011_anc_strict/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/011_anc_strict/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7914.02it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/000_baseline/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 128,
    "fp": 221,
    "fn": 186,
    "precision": 0.3667621776504298,
    "recall": 0.40764331210191085,
    "f1": 0.38612368024132726
  },
  "concept_level": {
    "tp": 263.85,
    "fp": 241.25000000000003,
    "fn": 255.25000000000003,
    "precision": 0.5223718075628588,
    "recall": 0.50828356771335,
    "f1": 0.5152314001171646
  }
}
Wrote details: results/20260414_isolation/000_baseline/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/000_baseline/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 128,
    "fp": 221,
    "fn": 186,
    "precision": 0.3667621776504298,
    "recall": 0.40764331210191085,
    "f1": 0.38612368024132726
  },
  "concept_level": {
    "tp": 263.85,
    "fp": 241.25000000000003,
    "fn": 255.25000000000003,
    "precision": 0.5223718075628588,
    "recall": 0.50828356771335,
    "f1": 0.5152314001171646
  }
}
Wrote evaluation metrics to: results/20260414_isolation/000_baseline/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/000_baseline/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 8633.99it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/001_strict_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 216,
    "fn": 181,
    "precision": 0.38108882521489973,
    "recall": 0.42356687898089174,
    "f1": 0.4012066365007541
  },
  "concept_level": {
    "tp": 284.8,
    "fp": 238.3,
    "fn": 234.3,
    "precision": 0.5444465685337412,
    "recall": 0.5486418801772298,
    "f1": 0.5465361734791787
  }
}
Wrote details: results/20260414_isolation/001_strict_only/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/001_strict_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 133,
    "fp": 216,
    "fn": 181,
    "precision": 0.38108882521489973,
    "recall": 0.42356687898089174,
    "f1": 0.4012066365007541
  },
  "concept_level": {
    "tp": 284.8,
    "fp": 238.3,
    "fn": 234.3,
    "precision": 0.5444465685337412,
    "recall": 0.5486418801772298,
    "f1": 0.5465361734791787
  }
}
Wrote evaluation metrics to: results/20260414_isolation/001_strict_only/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/001_strict_only/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 8057.58it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/010_anc_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 129,
    "fp": 220,
    "fn": 185,
    "precision": 0.36962750716332377,
    "recall": 0.410828025477707,
    "f1": 0.38914027149321273
  },
  "concept_level": {
    "tp": 271.5,
    "fp": 238.70000000000005,
    "fn": 247.70000000000005,
    "precision": 0.5321442571540572,
    "recall": 0.522919876733436,
    "f1": 0.5274917427627744
  }
}
Wrote details: results/20260414_isolation/010_anc_only/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/010_anc_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 129,
    "fp": 220,
    "fn": 185,
    "precision": 0.36962750716332377,
    "recall": 0.410828025477707,
    "f1": 0.38914027149321273
  },
  "concept_level": {
    "tp": 271.5,
    "fp": 238.70000000000005,
    "fn": 247.70000000000005,
    "precision": 0.5321442571540572,
    "recall": 0.522919876733436,
    "f1": 0.5274917427627744
  }
}
Wrote evaluation metrics to: results/20260414_isolation/010_anc_only/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/010_anc_only/evaluation_details_coupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7964.17it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/100_bm25_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 219,
    "fn": 184,
    "precision": 0.37249283667621774,
    "recall": 0.4140127388535032,
    "f1": 0.39215686274509803
  },
  "concept_level": {
    "tp": 261.19999999999993,
    "fp": 241.90000000000003,
    "fn": 257.90000000000003,
    "precision": 0.5191810773206121,
    "recall": 0.503178578308611,
    "f1": 0.5110545881432205
  }
}
Wrote details: results/20260414_isolation/100_bm25_only/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260414_isolation/100_bm25_only/aggregated_results_rewrite.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 130,
    "fp": 219,
    "fn": 184,
    "precision": 0.37249283667621774,
    "recall": 0.4140127388535032,
    "f1": 0.39215686274509803
  },
  "concept_level": {
    "tp": 261.19999999999993,
    "fp": 241.90000000000003,
    "fn": 257.90000000000003,
    "precision": 0.5191810773206121,
    "recall": 0.503178578308611,
    "f1": 0.5110545881432205
  }
}
Wrote evaluation metrics to: results/20260414_isolation/100_bm25_only/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260414_isolation/100_bm25_only/evaluation_details_coupled.csv

In [57]:
from agent_runner import evaluate_aggregated_predictions
import json
import os
# gold_csv = "results/contra_gold_100_2.csv"
gold_csv = "results/contra_gold_100_3.csv"
# aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
# eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
# eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"
targets = ["results/20260415_isolation"]
bools = [True, False]
for target in targets:
    for decoupled in bools:
        for root, dirs, files in os.walk(target):
            for filename in files:
                if filename == "aggregated_hits.csv":
                    aggregated_csv = os.path.join(root, filename)
                    json_name = "evaluation_metrics_decoupled.json" if decoupled else "evaluation_metrics_coupled.json"
                    csv_name = "evaluation_details_decoupled.csv" if decoupled else "evaluation_details_coupled.csv"
                    eval_json = os.path.join(root, json_name)
                    eval_details_csv = os.path.join(root, csv_name)
                    metrics = evaluate_aggregated_predictions(
                                pred_csv=aggregated_csv,
                                gold_csv=gold_csv,
                                out_json=eval_json,
                                out_details_csv=eval_details_csv,
                                decoupled=decoupled,
                                min_pair_score=0.8
                            )
                    print(json.dumps(metrics, indent=2))
                    print(f"Wrote evaluation metrics to: {eval_json}")
                    print(f"Wrote evaluation details to: {eval_details_csv}")

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 9192.83it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260415_isolation/101_bm25_strict/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 136,
    "fp": 96,
    "fn": 96,
    "precision": 0.5862068965517241,
    "recall": 0.5862068965517241,
    "f1": 0.5862068965517241
  },
  "concept_level": {
    "tp": 288.55,
    "fp": 55.449999999999996,
    "fn": 89.45,
    "precision": 0.8388081395348838,
    "recall": 0.7633597883597883,
    "f1": 0.7993074792243767
  }
}
Wrote details: results/20260415_isolation/101_bm25_strict/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260415_isolation/101_bm25_strict/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 136,
    "fp": 96,
    "fn": 96,
    "precision": 0.5862068965517241,
    "recall": 0.5862068965517241,
    "f1": 0.5862068965517241
  },
  "concept_level": {
    "tp": 288.55,
    "fp": 55.449999999999996,
    "fn": 89.45,
    "precision": 0.8388081395348838,
    "recall": 0.7633597883597883,
    "f1": 0.7993074792243767
  }
}
Wrote evaluation metrics to: results/20260415_isolation/101_bm25_strict/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260415_isolation/101_bm25_strict/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7665.47it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260415_isolation/110_bm25_anc/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 117,
    "fp": 115,
    "fn": 115,
    "precision": 0.5043103448275862,
    "recall": 0.5043103448275862,
    "f1": 0.5043103448275862
  },
  "concept_level": {
    "tp": 241.85,
    "fp": 74.15,
    "fn": 136.15,
    "precision": 0.7653481012658228,
    "recall": 0.6398148148148148,
    "f1": 0.6969740634005763
  }
}
Wrote details: results/20260415_isolation/110_bm25_anc/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260415_isolation/110_bm25_anc/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 117,
    "fp": 115,
    "fn": 115,
    "precision": 0.5043103448275862,
    "recall": 0.5043103448275862,
    "f1": 0.5043103448275862
  },
  "concept_level": {
    "tp": 241.85,
    "fp": 74.15,
    "fn": 136.15,
    "precision": 0.7653481012658228,
    "recall": 0.6398148148148148,
    "f1": 0.6969740634005763
  }
}
Wrote evaluation metrics to: results/20260415_isolation/110_bm25_anc/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260415_isolation/110_bm25_anc/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 4158.65it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260415_isolation/111_all_on/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 137,
    "fp": 95,
    "fn": 95,
    "precision": 0.5905172413793104,
    "recall": 0.5905172413793104,
    "f1": 0.5905172413793104
  },
  "concept_level": {
    "tp": 287.40000000000003,
    "fp": 56.599999999999994,
    "fn": 90.60000000000002,
    "precision": 0.8354651162790698,
    "recall": 0.7603174603174603,
    "f1": 0.7961218836565097
  }
}
Wrote details: results/20260415_isolation/111_all_on/evaluation_details_decoupled.csv
{
  "inputs": {
    "pred_csv": "results/20260415_isolation/111_all_on/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_3.csv",
    "gold_rows_total": 387,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 73,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": true,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 232,
    "fp": 117,
    "fn": 82,
    "precision": 0.664756446991404,
    "recall": 0.7388535031847133,
    "f1": 0.6998491704374058
  },
  "contraindication_level": {
    "tp": 137,
    "fp": 95,
    "fn": 95,
    "precision": 0.5905172413793104,
    "recall": 0.5905172413793104,
    "f1": 0.5905172413793104
  },
  "concept_level": {
    "tp": 287.40000000000003,
    "fp": 56.599999999999994,
    "fn": 90.60000000000002,
    "precision": 0.8354651162790698,
    "recall": 0.7603174603174603,
    "f1": 0.7961218836565097
  }
}
Wrote evaluation metrics to: results/20260415_isolation/111_all_on/evaluation_metrics_decoupled.json
Wrote evaluation details to: results/20260415_isolation/111_all_on/evaluation_details_decoupled.csv
Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 5693.46it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).

Traceback (most recent call last):
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 858, in <module>
    main()
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 657, in main
    compute_tiered_concept_metrics(
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 325, in compute_tiered_concept_metrics
    [
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 326, in <listcomp>
    [
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 327, in <listcomp>
    concept_similarity_score(
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 296, in concept_similarity_score
    lca = max(common, key=lambda a: get_concept_depth(a, rel_df_indexed))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 296, in <lambda>
    lca = max(common, key=lambda a: get_concept_depth(a, rel_df_indexed))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 247, in get_concept_depth
    anc = _cached_ancestors_with_depth(concept_id, rel_df_indexed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wmanuel3/VaxMapperRepo/evaluate_agg_results_3.py", line 236, in _cached_ancestors_with_depth
    _anc_depth_cache[concept_id] = get_ancestors_with_depth(concept_id, rel_df_indexed)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wmanuel3/VaxMapperRepo/VaxMapper/src/utils/snomed_utils.py", line 426, in get_ancestors_with_depth
    parents = snomed_rel_df.loc[[current], "destinationId"].tolist()
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1200, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1386, in _getitem_tuple
    return self._getitem_lowerdim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1117, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1207, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1438, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1378, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexing.py", line 1576, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6300, in _get_indexer_strict
    keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 4296, in _reindex_non_unique
    indexer, missing = self.get_indexer_non_unique(target)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6249, in get_indexer_non_unique
    indexer, missing = self._engine.get_indexer_non_unique(tgt_values)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

In [5]:
import json
import os
import pandas as pd

target = "results/20260414_isolation"
rows = []

for root, dirs, files in os.walk(target):
    for filename in files:
        if filename == "evaluation_metrics_2.json":
            method = os.path.basename(root)
            eval_json = os.path.join(root, filename)

            with open(eval_json) as f:
                metrics = json.load(f)

            rows.append({
                ("method", ""): method,

                ("extraction", "precision"): metrics.get("extraction_level", {}).get("precision"),
                ("extraction", "recall"): metrics.get("extraction_level", {}).get("recall"),
                ("extraction", "f1"): metrics.get("extraction_level", {}).get("f1"),

                ("concept", "precision"): metrics.get("concept_level", {}).get("precision"),
                ("concept", "recall"): metrics.get("concept_level", {}).get("recall"),
                ("concept", "f1"): metrics.get("concept_level", {}).get("f1"),

                ("contraindication", "precision"): metrics.get("contraindication_level", {}).get("precision"),
                ("contraindication", "recall"): metrics.get("contraindication_level", {}).get("recall"),
                ("contraindication", "f1"): metrics.get("contraindication_level", {}).get("f1"),
            })

df = pd.DataFrame(rows)
df = df.sort_values(("method", "")).reset_index(drop=True)
df

,"(method, )","(extraction, precision)","(extraction, recall)","(extraction, f1)","(concept, precision)","(concept, recall)","(concept, f1)","(contraindication, precision)","(contraindication, recall)","(contraindication, f1)"
0,000_baseline,0.664756,0.738854,0.699849,0.834234,0.734921,0.781435,0.551724,0.551724,0.551724
1,001_strict_only,0.664756,0.738854,0.699849,0.849713,0.782275,0.814601,0.573276,0.573276,0.573276
2,010_anc_only,0.664756,0.738854,0.699849,0.846142,0.754365,0.797622,0.556034,0.556034,0.556034
3,011_anc_strict,0.662824,0.732484,0.695915,0.862500,0.793316,0.826462,0.578261,0.578261,0.578261
4,100_bm25_only,0.664756,0.738854,0.699849,0.831325,0.730159,0.777465,0.560345,0.560345,0.560345
5,101_bm25_strict,0.664756,0.738854,0.699849,0.835942,0.762963,0.797787,0.564655,0.564655,0.564655
6,110_bm25_anc,0.664756,0.738854,0.699849,0.827126,0.746164,0.784562,0.560345,0.560345,0.560345
7,111_all_on,0.664756,0.738854,0.699849,0.834091,0.776720,0.804384,0.568966,0.568966,0.568966

In [56]:
df

,"(method, )","(extraction, precision)","(extraction, recall)","(extraction, f1)","(concept, precision)","(concept, recall)","(concept, f1)","(contraindication, precision)","(contraindication, recall)","(contraindication, f1)"
0,000_baseline,0.664756,0.738854,0.699849,0.792104,0.697831,0.741985,0.551724,0.551724,0.551724
1,001_strict_only,0.664756,0.738854,0.699849,0.818156,0.753240,0.784357,0.573276,0.573276,0.573276
2,010_anc_only,0.664756,0.738854,0.699849,0.805160,0.717874,0.759016,0.556034,0.556034,0.556034
3,011_anc_strict,0.662824,0.732484,0.695915,0.829895,0.763362,0.795239,0.578261,0.578261,0.578261
4,100_bm25_only,0.664756,0.738854,0.699849,0.786510,0.690823,0.735567,0.560345,0.560345,0.560345
5,101_bm25_strict,0.664756,0.738854,0.699849,0.798754,0.729040,0.762306,0.564655,0.564655,0.564655
6,110_bm25_anc,0.664756,0.738854,0.699849,0.782825,0.706240,0.742563,0.560345,0.560345,0.560345
7,111_all_on,0.664756,0.738854,0.699849,0.795713,0.741010,0.767388,0.568966,0.568966,0.568966

In [22]:
df.to_csv("results/20260414_isolation/summary_results_2.csv", index=False)

In [23]:
from evaluate_agg_results_3 import compute_tiered_concept_metrics

In [ ]:
compute_tiered_concept_metrics([])

In [ ]:
# presentation evaluation:

In [ ]:
from agent_runner import evaluate_aggregated_predictions
import json
import os
# gold_csv = "results/contra_gold_100_2.csv"
# medgemma baseline
gold_csv = "results/contra_gold_100_2.csv"
# aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
# eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
# eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"
targets = ["results/20260402"]
bools = [False]
for target in targets:
    for decoupled in bools:
        for root, dirs, files in os.walk(target):
            for filename in files:
                if filename == "aggregated_hits.csv":
                    aggregated_csv = os.path.join(root, filename)
                    json_name = "evaluation_metrics_decoupled.json" if decoupled else "evaluation_metrics_coupled.json"
                    csv_name = "evaluation_details_decoupled.csv" if decoupled else "evaluation_details_coupled.csv"
                    eval_json = os.path.join(root, json_name)
                    eval_details_csv = os.path.join(root, csv_name)
                    metrics = evaluate_aggregated_predictions(
                                pred_csv=aggregated_csv,
                                gold_csv=gold_csv,
                                out_json=eval_json,
                                out_details_csv=eval_details_csv,
                                decoupled=decoupled,
                                min_pair_score=0.8
                            )
                    print(json.dumps(metrics, indent=2))
                    print(f"Wrote evaluation metrics to: {eval_json}")
                    print(f"Wrote evaluation details to: {eval_details_csv}")

/home/srv-wmanuel3/miniconda3/envs/splmap/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 8588.10it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260402/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_2.csv",
    "gold_rows_total": 405,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 91,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 177,
    "fp": 183,
    "fn": 137,
    "precision": 0.49166666666666664,
    "recall": 0.5636942675159236,
    "f1": 0.5252225519287833
  },
  "contraindication_level": {
    "tp": 86,
    "fp": 274,
    "fn": 228,
    "precision": 0.2388888888888889,
    "recall": 0.27388535031847133,
    "f1": 0.255192878338279
  },
  "concept_level": {
    "tp": 156.49999999999997,
    "fp": 309.5999999999999,
    "fn": 360.5999999999999,
    "precision": 0.33576485732675393,
    "recall": 0.3026493908334945,
    "f1": 0.3183482506102523
  }
}
Wrote details: results/20260402/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260402/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_2.csv",
    "gold_rows_total": 405,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 91,
    "discard_na_gold_expression": true,
    "pred_rows": 385,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 177,
    "fp": 183,
    "fn": 137,
    "precision": 0.49166666666666664,
    "recall": 0.5636942675159236,
    "f1": 0.5252225519287833
  },
  "contraindication_level": {
    "tp": 86,
    "fp": 274,
    "fn": 228,
    "precision": 0.2388888888888889,
    "recall": 0.27388535031847133,
    "f1": 0.255192878338279
  },
  "concept_level": {
    "tp": 156.49999999999997,
    "fp": 309.5999999999999,
    "fn": 360.5999999999999,
    "precision": 0.33576485732675393,
    "recall": 0.3026493908334945,
    "f1": 0.3183482506102523
  }
}
Wrote evaluation metrics to: results/20260402/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260402/evaluation_details_coupled.csv

In [ ]:
from agent_runner import evaluate_aggregated_predictions
import json
import os
# gold_csv = "results/contra_gold_100_2.csv"
# gemma4 baseline
gold_csv = "results/contra_gold_100_2.csv"
# aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
# eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
# eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"
targets = ["results/20260406"]
bools = [False]
for target in targets:
    for decoupled in bools:
        for root, dirs, files in os.walk(target):
            for filename in files:
                if filename == "aggregated_hits.csv":
                    aggregated_csv = os.path.join(root, filename)
                    json_name = "evaluation_metrics_decoupled.json" if decoupled else "evaluation_metrics_coupled.json"
                    csv_name = "evaluation_details_decoupled.csv" if decoupled else "evaluation_details_coupled.csv"
                    eval_json = os.path.join(root, json_name)
                    eval_details_csv = os.path.join(root, csv_name)
                    metrics = evaluate_aggregated_predictions(
                                pred_csv=aggregated_csv,
                                gold_csv=gold_csv,
                                out_json=eval_json,
                                out_details_csv=eval_details_csv,
                                decoupled=decoupled,
                                min_pair_score=0.8
                            )
                    print(json.dumps(metrics, indent=2))
                    print(f"Wrote evaluation metrics to: {eval_json}")
                    print(f"Wrote evaluation details to: {eval_details_csv}")

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 7885.78it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260406/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_2.csv",
    "gold_rows_total": 405,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 91,
    "discard_na_gold_expression": true,
    "pred_rows": 391,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 239,
    "fp": 116,
    "fn": 75,
    "precision": 0.6732394366197183,
    "recall": 0.7611464968152867,
    "f1": 0.7144992526158445
  },
  "contraindication_level": {
    "tp": 121,
    "fp": 234,
    "fn": 193,
    "precision": 0.3408450704225352,
    "recall": 0.3853503184713376,
    "f1": 0.36173393124065767
  },
  "concept_level": {
    "tp": 230.60000000000002,
    "fp": 260.4,
    "fn": 286.3999999999999,
    "precision": 0.469653767820774,
    "recall": 0.44603481624758223,
    "f1": 0.4575396825396826
  }
}
Wrote details: results/20260406/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260406/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_2.csv",
    "gold_rows_total": 405,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 91,
    "discard_na_gold_expression": true,
    "pred_rows": 391,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 239,
    "fp": 116,
    "fn": 75,
    "precision": 0.6732394366197183,
    "recall": 0.7611464968152867,
    "f1": 0.7144992526158445
  },
  "contraindication_level": {
    "tp": 121,
    "fp": 234,
    "fn": 193,
    "precision": 0.3408450704225352,
    "recall": 0.3853503184713376,
    "f1": 0.36173393124065767
  },
  "concept_level": {
    "tp": 230.60000000000002,
    "fp": 260.4,
    "fn": 286.3999999999999,
    "precision": 0.469653767820774,
    "recall": 0.44603481624758223,
    "f1": 0.4575396825396826
  }
}
Wrote evaluation metrics to: results/20260406/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260406/evaluation_details_coupled.csv

In [ ]:
from agent_runner import evaluate_aggregated_predictions
import json
import os
# gold_csv = "results/contra_gold_100_2.csv"
# qwen 3.5
gold_csv = "results/contra_gold_100_2.csv"
# aggregated_csv = "results/20260407/gemma4_bm25_ancestor_paths/aggregated_hits.csv"
# eval_json = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_metrics_gemma4dcf.json"
# eval_details_csv = "results/20260407/gemma4_bm25_ancestor_paths/evaluation_details_gemma4dcf.csv"
targets = ["results/20260401"]
bools = [False]
for target in targets:
    for decoupled in bools:
        for root, dirs, files in os.walk(target):
            for filename in files:
                if filename == "aggregated_hits.csv":
                    aggregated_csv = os.path.join(root, filename)
                    json_name = "evaluation_metrics_decoupled.json" if decoupled else "evaluation_metrics_coupled.json"
                    csv_name = "evaluation_details_decoupled.csv" if decoupled else "evaluation_details_coupled.csv"
                    eval_json = os.path.join(root, json_name)
                    eval_details_csv = os.path.join(root, csv_name)
                    metrics = evaluate_aggregated_predictions(
                                pred_csv=aggregated_csv,
                                gold_csv=gold_csv,
                                out_json=eval_json,
                                out_details_csv=eval_details_csv,
                                decoupled=decoupled,
                                min_pair_score=0.8
                            )
                    print(json.dumps(metrics, indent=2))
                    print(f"Wrote evaluation metrics to: {eval_json}")
                    print(f"Wrote evaluation details to: {eval_details_csv}")

Loading model google/embeddinggemma-300m...

Loading weights: 100%|██████████| 314/314 [00:00<00:00, 10725.46it/s]

Model google/embeddinggemma-300m loaded to cuda:0 successfully.
Tiered concept scoring enabled (631,617 IS-A rows loaded).
{
  "inputs": {
    "pred_csv": "results/20260401/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_2.csv",
    "gold_rows_total": 405,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 91,
    "discard_na_gold_expression": true,
    "pred_rows": 392,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 231,
    "fp": 129,
    "fn": 83,
    "precision": 0.6416666666666667,
    "recall": 0.7356687898089171,
    "f1": 0.685459940652819
  },
  "contraindication_level": {
    "tp": 122,
    "fp": 238,
    "fn": 192,
    "precision": 0.3388888888888889,
    "recall": 0.3885350318471338,
    "f1": 0.3620178041543027
  },
  "concept_level": {
    "tp": 234.19999999999996,
    "fp": 282.8,
    "fn": 282.79999999999995,
    "precision": 0.45299806576402313,
    "recall": 0.45299806576402324,
    "f1": 0.4529980657640232
  }
}
Wrote details: results/20260401/evaluation_details_coupled.csv
{
  "inputs": {
    "pred_csv": "results/20260401/aggregated_hits.csv",
    "gold_csv": "results/contra_gold_100_2.csv",
    "gold_rows_total": 405,
    "gold_rows_used": 314,
    "gold_rows_dropped_na_expression": 91,
    "discard_na_gold_expression": true,
    "pred_rows": 392,
    "gold_unique_spl": 100,
    "semantic_matching_enabled": true,
    "semantic_matching_unavailable_reasons": [],
    "st_model_id": "google/embeddinggemma-300m",
    "alpha": 0.85,
    "beta": 0.15,
    "min_pair_score": 0.8,
    "decoupled": false,
    "assignment_method": "hungarian",
    "tiered_concept_scoring": true,
    "hierarchy_partial_score": 0.0
  },
  "extraction_level": {
    "tp": 231,
    "fp": 129,
    "fn": 83,
    "precision": 0.6416666666666667,
    "recall": 0.7356687898089171,
    "f1": 0.685459940652819
  },
  "contraindication_level": {
    "tp": 122,
    "fp": 238,
    "fn": 192,
    "precision": 0.3388888888888889,
    "recall": 0.3885350318471338,
    "f1": 0.3620178041543027
  },
  "concept_level": {
    "tp": 234.19999999999996,
    "fp": 282.8,
    "fn": 282.79999999999995,
    "precision": 0.45299806576402313,
    "recall": 0.45299806576402324,
    "f1": 0.4529980657640232
  }
}
Wrote evaluation metrics to: results/20260401/evaluation_metrics_coupled.json
Wrote evaluation details to: results/20260401/evaluation_details_coupled.csv